### ISSUE TITLE
Support for large size message

### ISSUE THREAD

**Issue by ksinghbora** [reactor/reactor-kafka#104]
Is there any consideration to handle large size messages (>1 MB) by breaking this into chunk and reassemble while consuming or any other solution?
If not then, any idea to use other wrapper library with this (like li-apache-kafka-clients)?

**Comment by bsideup** [comment]
@ksinghbora 
Reactor Kafka implements a wrapper around the official Kafka Client and inherits the same semantics and considerations.

You can provide your own KafkaConsumer/KafkaProducer factory in case you need to customize and/or wrap them.

**Comment by ksinghbora** [comment]
Thanks @bsideup .
