### ISSUE TITLE
KafkaReceiver not disposed with empty Flux or on Fail

### ISSUE THREAD

**Issue by quazard** [reactor/reactor-kafka#107]
I am facing a problem when i call `create()` and `receive()` operators and Kafka broker returns 0 records, since this is an empty Flux, the signal is not declared as terminated and `dispose()` method is never called within `DefaultKafkaReceiver` class. Subsequent `create()` and `receive()` operations are enqueued indefinitely.

```
example:
Kafka broker has 5 records, offsets from 0 to 4 in partition 0 for some topic
KafkaReceiver is provided with an offset out of sight (offset 9999), calling create() and receive()
Expect the consumer to be disposed and call again create()/receive() with a valid offset, ie. 1
```
```java
KafkaReceiver
   .create(
       receiverOptions
           .addAssignListener(
               partitions -> partitions.forEach( p -> p.seek(9999) )
           )
           .subscription(Collections.singleton("topic"))
   )
   .receive()
```

This also happens when an Exception is thrown within `DefaultKafkaReceiver` class and `fail(Throwable e)` method is called (same behavior as previously explained with dispose() method).

```
example:
defining AUTO_OFFSET_RESET_CONFIG property as "none" and getting an offset out of sight, throws org.apache.kafka.clients.consumer.OffsetOutOfRangeException
```
```java
Map<String, Object> props = new HashMap<>();
props.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "none");
... some other properties
```

Still trying to get familiar with this dependency code, hope the examples are clear.

Using:
Spring Boot 2.1.6.RELEASE
Reactor Kafka 1.1.1.RELEASE

**Comment by bsideup** [comment]
> since this is an empty Flux, the signal is not declared as terminated and dispose() method is never called

This is not an empty `Flux`, but a `Flux` that has nothing to produce (yet), so it will wait for records. It is not expected to automatically terminate.
