### ISSUE TITLE
Bigger offset could be overridden by smaller one in CommittableBatch

### ISSUE THREAD

**Issue by justinplus** [reactor/reactor-kafka#117]
Bigger offset could be overridden by smaller one in `CommittableBatch#updateOffset(TopicPartition topicPartition, long offset)`

## Description

Given offset `1222`, `1223`, when calling `updateOffset` with
1. `updateOffset(oneTopicPartition, 1223)`
2. `updateOffset(oneTopicPartition, 1222)`

The latest consumed offset should be `1223` but it's `1222`, since the method updates the `consumedOffsets` directly without checking.

see: https://github.com/reactor/reactor-kafka/blob/master/src/main/java/reactor/kafka/receiver/internals/CommittableBatch.java#L43-L44

```java
public synchronized int updateOffset(TopicPartition topicPartition, long offset) {
  if (consumedOffsets.put(topicPartition, offset) != (Long) offset)
      batchSize++;
  return batchSize;
}
```

## Steps to Reproduce

```java
@Test
public void repoCase() {
  final TopicPartition tp = new TopicPartition("test", 0);
  final CommittableBatch batch = new CommittableBatch();
  batch.updateOffset(tp, 1223);
  batch.updateOffset(tp, 1222);
  CommittableBatch.CommitArgs commitArgs = batch.getAndClearOffsets();

  // commit offset = consumed offset +1, and thus
  // 1224 = 1223 + 1
  assertEquals(1224L, commitArgs.offsets().get(tp).offset());
}
```

## Possible Solution

```java
public synchronized int updateOffset(TopicPartition topicPartition, long offset) {
  final Long previous = consumedOffsets.get(topicPartition);
  if (null == previous) {
    consumedOffsets.put(topicPartition, offset);
    batchSize++;
  } else {
    if (offset > previous) {
      consumedOffsets.put(topicPartition, offset);
      batchSize += offset - previous;
    }
  }

  return batchSize;
}
```

## Your Environment

* Reactor version(s) used: 1.2.1-release

**Comment by bsideup** [comment]
It would be limiting if we disallow `updateOffset` override previously set value. If the user decides to update to to an older offset - they should be able to do so. You can easily add a check on your side.
