### ISSUE TITLE
Half of the Consumers in a particular ConsumerGroup don't receive messages.

### ISSUE THREAD

**Issue by apurvjain17** [reactor/reactor-kafka#122]
Hi,

We are using reactor kafka. Our topic has 5 partitions, so we create 5 consumers at the same time.
`    public Flux<ReceiverRecord<String, String>> createConsumerFlux(){

        var receiverOptions = ReceiverOptions.<String, String>create(getConsumerProperties())
                .addAssignListener(partitions -> log.info("Partitions Assigned "+ partitions.toString()))
                .addRevokeListener(partitions ->  log.info("Partitions Revoked "+ partitions.toString()))
                .subscription(Collections.singleton(appConfig.getInitialScanTopicName()));

        return KafkaReceiver.create(receiverOptions).receive();

    }
`

## Expected Behavior
Now we expect kafka to read messages from all the five partitions. However, it randomly picks any 2 or 3 partitions and starts reading messages from those only. 

Rest of the time we keep receiving these logs :- 
` Node 262 was unable to process the fetch request with (sessionId=1302, epoch=156): FETCH_SESSION_ID_NOT_FOUND.
`

* Reactor version(s) used: 1.1.0.RELEASE
* Other relevant libraries versions (eg. `netty`, ...): Netty Spring-Boot-WebFlux:2.2.1.RELEASE
* JVM version (`javar -version`): 11

**Comment by meghagupta9** [comment]
Did you find any solution? I am also facing it.

**Comment by meghagupta9** [comment]
error: *Node 235175261 was unable to process the fetch request with (sessionId=1809039830, epoch=77): FETCH_SESSION_ID_NOT_FOUND.
**

**Comment by sjuyal12** [comment]
I am using addAssignListener, but I cant see multiple consumers getting created. Am I missing something ?

**Comment by rodrigocprates** [comment]
+1

**Comment by tcalsavara** [comment]
+1

**Comment by geraldofcneto** [comment]
+1

**Comment by bsideup** [comment]
Please do not comment with "+1" but add ":+1:" reaction on the issue (that will allow us to search for most reacted issues, btw)

**Comment by bsideup** [comment]
@apurvjain17 this works as expected. Kafka will balance the load between multiple Consumers in the same group. See Kafka's docs on how partitions are assigned.

**Comment by Nitss10** [comment]
Hi @bsideup, your point makes sense. But whatever number of partitions I create, the same number of consumers are created automatically. How do I limit the number of consumers?

**Comment by garyrussell** [comment]
`receive()` will only create one consumer.
