### ISSUE TITLE
IncompatibleClassChangeError on running Consumer

### ISSUE THREAD

**Issue by acudupa** [reactor/reactor-kafka#125]
I am trying to use the 
`        <dependency>
<groupId>io.projectreactor</groupId>
 <artifactId>reactor-core</artifactId>
<version>3.3.2.RELEASE</version>
</dependency>`
and build a simple consumer that subscribes to a topic. But when I call,
`receiverOptions.subscription(Collections.singleton(topic)`
it throws

`Caused by: java.lang.IncompatibleClassChangeError: Found class reactor.kafka.receiver.ReceiverOptions, but interface was expected`

I have tried clean builds using mvn, invalidated cache and restarted intellij.
Any help with this will be greatly appreciated.

**Comment by Fermi-4** [comment]
Bump

**Comment by bsideup** [comment]
`ReceiverOptions` is indeed an interface. Please check your code, perhaps you're using some library that is linked to some super old version of `reactor-kafka`.
