### ISSUE TITLE
Investigate test issue with KafkaSenderTest#sendWithResponse

### ISSUE THREAD

**Issue by ilayaperumalg** [reactor/reactor-kafka#13]
The log has this message a lot:

```
[kafka-producer-network-thread | producer-1] [org.apache.kafka.clients.NetworkClient] WARN Connection to node 0 could not be established. Broker may not be available. 
```

**Comment by simonbasle** [comment]
@ilayaperumalg the tests were just logging these messages locally, but ultimately passing.

**Comment by ilayaperumalg** [comment]
For each test, we start/stop the embedded Kafka server (as it is needed for the usecases). 

The `Connection to node 0 could not be established. Broker may not be available. ` log message suggests that the producer thread still active while the broker which is already shutdown by the test.  

There is also a controller broker state info thread active as well. 

We need to provide a way to check the shutdown is triggered only after the associated resources are cleaned (for both test pass/fail scenarios).

**Comment by ilayaperumalg** [comment]
It turns out that these WARN log messages are still valid as we try to introduce error scenarios as in [here](https://github.com/reactor/reactor-kafka/blob/master/src/test/java/reactor/kafka/sender/KafkaSenderTest.java#L541)  in some of the tests. Hence, this issue can be closed.

**Comment by ilayaperumalg** [comment]
Got this confirmed with Rajini as well. Thank you @rajinisivaram
