### ISSUE TITLE
documentation incorrect for Reactive pipeline with Kafka Source?

### ISSUE THREAD

**Issue by peterfigure** [reactor/reactor-kafka#144]
https://projectreactor.io/docs/kafka/snapshot/reference/#kafka-source

Line 5: `.doOnSuccess(r -> m.receiverOffset().commit().block()));`

As the example stands there it fails at runtime because `.block()` cannot be called when using a `Schedulers.newSingle("sample", true)`:

```
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-tcp-nio-1
Caused by: java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-tcp-nio-1
```

**Comment by architmmmec** [comment]
You can go for asynchronous commit
