### ISSUE TITLE
Can you please add SOCKS PROXY support

### ISSUE THREAD

**Issue by jfsanchez-gh** [reactor/reactor-kafka#149]
Sometimes you need to access your Kafka cluster by going though a PROXY server.
Right now it is a nightmare to implement this.

**Comment by bsideup** [comment]
`reactor-kafka` uses Kafka's official client (and allows setting properties on it and/or provide a consumer factory). Please refer to Kafka's docs on how to setup SOCKS proxy.

**Comment by jfsanchez-gh** [comment]
Can you please share the section where I can read about it? So far I just cant find it. Thx
