### ISSUE TITLE
Question: acknowledging ReceiverRecords while filtering or handling errors

### ISSUE THREAD

**Issue by tchupp** [reactor/reactor-kafka#155]
In some situations, it makes sense to use `Flux<ReceiverRecord<K, V>>.filter()` to skip processing of some records.

Since Kafka works off the idea of commit offsets instead of acknowledging specific records, I'm curious about the expected behavior if you fail to call `.acknowledge()` for a given offset.

Contrived example:
```java
Flux.defer(receiver::receive)
  .filter(record -> record.value().nullableProperty.isPresent()) // <- record is ignored
  .flatMap(record -> {
    db.save(record.value())
      .flatMap(() -> record.offset().acknowledge()) // record is not acknowledged if saving fails
      .onErrorResumeNext(Flowable.empty())
  })
  .subscribe(record -> System.out.printf("Processed %s%n", record.value()));
```

For the following questions let's assume we have one partition, and have records with offsets 1 through 5.

By default, `flatMap` has unbounded concurrency; this means that `db.save` could get called for multiple records in parallel, meaning `.acknowledge()` could be called out of order.
1. Are there any implications to acking messages out of order? (ie. offset 3, then offset 2, then 5, then 4, then 1)

When filtering, we might skip acking certain records. (ie. offsets 1, 2, 4, and 5 are acked)
2. When the commit happens, will it commit up to the first gap (commit up to offset 2)? or will it commit up to the last ack'ed offset (commit up to offset 5)?

**Comment by garyrussell** [comment]
See the javadocs for `ReceiverOffset.acknowledge()`; specifically

>When an offset is acknowledged, it is assumed that all records in this partition up to and including this offset have been processed.

Managing offsets is tricky when you consume asynchronously with any mechanism.

I just looked a the `CommittableBatch` and it only tracks one offset per topic/partition so it's important to acknowledge in order. A lot more sophistication would be required there to handle out of order acknowledgments. And, even then, the possibility of redelivery of already processed records would be increased.

In the case of filtering, the offsets will remain uncommitted and will effectively be committed when the next unfiltered record is processed successfully and acknowledged. Therefore filtered records may be redelivered if the app crashes without processing any successful records after some have been filtered.

**Comment by tchupp** [comment]
So if I'm understanding correctly; acknowledging/committing is specific to a partition so it has to happen in order for that partition, but we could process each partition in parallel.

Would something safer look like this?
```java
Flux.defer(receiver::receive)
  .groupBy(record -> record.receiverOffset().topicPartition()) // <- add "groupBy(partition)"
  .flatMap(partition -> // <- run this in parallel for each partition
    partition
      .filter(record -> {
        var test = record.value().nullableProperty.isPresent();
        record.offset().acknowledge();
        return test;
      )
      .concatMap(record -> // <- change to concat, run in serial for each record in a given parition
        db.save(record.value())
          .onErrorResumeNext(Flowable.empty())
          .doOnNext(() -> record.offset().acknowledge())
      )
  )
  .subscribe(record -> System.out.printf("Processed %s%n", record.value()));

**Comment by garyrussell** [comment]
I am still getting up to speed on reactor (my expertise is Kafka), bit `concatMap`'s javadocs seem to imply it should work.

You would just risk getting the filtered records redelivered, but your filter strategy is static so that shouldn't hurt.
