### ISSUE TITLE
Why configuration enable.auto.commit is invalid

### ISSUE THREAD

**Issue by julang2** [reactor/reactor-kafka#163]
I tried to enable auto.offset.reset to submit automatically, but it still doesn't take effect?

## Expected Behavior

auto.offset.reset=true

## Actual Behavior

![image](https://user-images.githubusercontent.com/11583532/89532101-d78cb800-d823-11ea-9183-6014089ed159.png)

![image](https://user-images.githubusercontent.com/11583532/89532168-f2f7c300-d823-11ea-8ba4-48d438bbe507.png)

### pom.xml

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.3.1.RELEASE</version>
		<relativePath/> 
	</parent>

	<properties>
		<java.version>11</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>io.projectreactor.kafka</groupId>
			<artifactId>reactor-kafka</artifactId>
			<version>1.2.2.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>io.projectreactor.kafka</groupId>
			<artifactId>reactor-kafka-samples</artifactId>
			<version>1.2.2.RELEASE</version>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
	</dependencies>

### KafkaConsumerConfig

```
@Slf4j
@Configuration
public class KafkaConsumerConfig {

  @Resource
  private KafkaProperties kafkaproperties;

  private SimpleDateFormat dateFormat = new SimpleDateFormat("HH:mm:ss:SSS z dd MMM yyyy");


  @Bean
  public KafkaReceiver<String, Object> kafkaReceiver(
      ReceiverOptions<String, Object> receiverOptions) {
    return KafkaReceiver.create(receiverOptions);
  }

  /**
   * {@see CommonClientConfigs}
   */
  @Bean
  public ReceiverOptions receiverOptions() {
    Map<String, Object> options = new HashMap<>();
    options.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG,
        String.join(",", kafkaproperties.getBootstrapServers()));
    options.put(ConsumerConfig.CLIENT_ID_CONFIG, kafkaproperties.getConsumer().getClientId());
    options.put(ConsumerConfig.GROUP_ID_CONFIG, kafkaproperties.getConsumer().getGroupId());
    options.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG,
        kafkaproperties.getConsumer().getKeyDeserializer());
    options.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG,
        kafkaproperties.getConsumer().getValueDeserializer());
    options.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG,
        kafkaproperties.getConsumer().getAutoOffsetReset());
    options.put(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG,
        kafkaproperties.getConsumer().getEnableAutoCommit());
    options.putAll(kafkaproperties.getConsumer().getProperties());
    return ReceiverOptions.create(options)
        .subscription(Collections.singleton("Test-Topic"))
        .addAssignListener(partitions -> log.debug("onPartitionsAssigned {}", partitions))
        .addRevokeListener(partitions -> log.debug("onPartitionsRevoked {}", partitions));
  }

  @Bean
  public Disposable consumeMessages(KafkaReceiver<String, Object> kafkaReceiver) {
    Flux<ReceiverRecord<String, Object>> kafkaFlux = kafkaReceiver.receive();
    return kafkaFlux.subscribe(
        record -> {
          ReceiverOffset offset = record.receiverOffset();
          System.out
              .printf(
                  "Received message: topic-partition=%s offset=%d timestamp=%s key=%s value=%s\n",
                  offset.topicPartition(),
                  offset.offset(),
                  dateFormat.format(new Date(record.timestamp())),
                  record.key(),
                  record.value());
          offset.acknowledge();
        }
    );
  }

}
```

* Reactor version(s) used:
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`javar -version`):
* OS and version (eg `uname -a`):

**Comment by amrynsky** [comment]
@julang2  In reactor-kafka there is another abstraction on top of offsets - acknowledgment. Offsets for acknowledged records are committed periodically based on the configured commit interval and batch size, and `enable.auto.commit` is always set to `false` for the underlining kafka consumer. For details check [Controlling commit frequency](https://projectreactor.io/docs/kafka/release/reference/#_controlling_commit_frequency).
