### ISSUE TITLE
No Information about starting multiple consumers in a consumer group

### ISSUE THREAD

**Issue by sjuyal12** [reactor/reactor-kafka#167]
I went through the documentation but didnt find any mention of creating multiple consumers in a Consumer group to distribute the task of reading messages from different partitions. I know the process of doing it in Non reactive Kafka. Please let me know how we can achieve this in Reactive Kafka.

**Comment by bsideup** [comment]
@sjuyal12 there is no difference to the process of starting multiple consumers of the same consumer group compared to the original Kafka client. Reactor Kafka is built on top of it.

Also, please consider using Slack Overflow for questions.
