### ISSUE TITLE
Exceptions while creating producermono inside DefaultKafkaSender get silently ignored

### ISSUE THREAD

**Issue by gauravsindhwani** [reactor/reactor-kafka#169]
During my testing I gave a wrong Kafka bootstrap url. org.apache.kafka.clients.producer.KafkaProducer threw an exception which was ignored by DefaultKafkaSender.
Specifically the error comes on line number 96 in DefaultKafkaSender

```
this.producerMono = Mono
                .fromCallable(() -> {
                    Producer<K, V> producer =
                            producerFactory.createProducer(senderOptions); // exception due to unresolvable bootstrap url.
                    if (senderOptions.isTransactional()) {
                        log.info("Initializing transactions for producer {}",
                                senderOptions.transactionalId());
                        producer.initTransactions();
                    }
                    return producer;
                })
                .doOnSubscribe(s -> hasProducer.set(true))
                .cache()
                .as(flux -> {
                    return senderOptions.isTransactional()
                        ? flux.publishOn(senderOptions.scheduler())
                        : flux;
                });
```
  

## Expected Behavior

Exception should not be silently ignored and either subscriber or Publisher should be made aware.
## Actual Behavior

Exception is silently ignored
## Steps to Reproduce

Provide a unresolvable bootstrap url while initialising KafkaSender 

## Possible Solution

Since producerMono is created asynchronously, we can take a onError callback in SenderOptions, and invoke it on doOnError of producerMono
```
        this.producerMono = Mono
                .fromCallable(() -> {
                    Producer<K, V> producer =
                            producerFactory.createProducer(senderOptions);
                    if (senderOptions.isTransactional()) {
                        log.info("Initializing transactions for producer {}",
                                senderOptions.transactionalId());
                        producer.initTransactions();
                    }
                    return producer;
                })
                .doOnSubscribe(s -> hasProducer.set(true))
                .doOnError(e -> SenderOptions.onError(e)) // Something like this
                .cache()
                .as(flux -> {
                    return senderOptions.isTransactional()
                        ? flux.publishOn(senderOptions.scheduler())
                        : flux;
                });
```
## Your Environment

* Reactor version(s) used:v1.3.0-M1 
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`javar -version`):
* OS and version (eg `uname -a`):

**Comment by bsideup** [comment]
@gauravsindhwani it seems that it fails on `send`, which means that the exceptions are not silently ignored, just they are async.

Given that a custom scheduler can be provided and the initialization may happen asynchronously, we can't just block in `DefaultKafkaSender`. 

If you really need to fail early, here is a workaround:
```java
var sender = KafkaSender.create(senderOptions);
sender.send(Mono.empty()).blockFirst();
```
