### ISSUE TITLE
Update kafka-clients to the newer version

### ISSUE THREAD

**Issue by amrynsky** [reactor/reactor-kafka#178]
`reactor-kafka` depends on `kafka-clients:2.0.0` that is outdated. Having in mind that in many cases `reactor-kafka` is used in conjunction with `spring-boot` it makes sense to update the version. Usually, spring dependencies are managed  by BOM and newer version s forced anyway

```
...
+--- io.projectreactor.kafka:reactor-kafka -> 1.2.2.RELEASE
|    +--- io.projectreactor:reactor-core:3.3.2.RELEASE -> 3.3.6.RELEASE (*)
|    \--- org.apache.kafka:kafka-clients:2.0.0 -> 2.5.0
...
```

`spring-boot` is using the latest version [`kafka-clients:2.6.0`](https://github.com/spring-projects/spring-boot/blob/b69ede4556ec71c05c9498d37312b1f104659ab5/spring-boot-project/spring-boot-dependencies/build.gradle#L894)

**Comment by amrynsky** [comment]
@bsideup ready to submit PR if you agree

**Comment by bsideup** [comment]
@garyrussell WDYT?

**Comment by garyrussell** [comment]
Sorry; I was on PTO last week; yes; we should upgrade to 2.6.0.
