### ISSUE TITLE
Mechanism to Flush the KafkaSender's Producer

### ISSUE THREAD

**Issue by garyrussell** [reactor/reactor-kafka#185]
The ability to flush a producer is useful in some circumstances. When producing a lot of records, it can be useful to configure the `linger.ms` producer property; this is similar to the TCP Nagle's algorithm. The producer accumulates records locally until some limit is reached, or the linger times out.

It can be useful to flush the producer to avoid the delay, when you know you have sent all expected records (e.g. from a bounded `Flux`).

I recently encountered some code like this...

```java
DefaultKafkaSender<String, String> sender = new DefaultKafkaSender<>(
		reactor.kafka.sender.internals.ProducerFactory.INSTANCE, so);
Mono<SenderRecord<String, String, String>> sendMono =
		Mono.just(SenderRecord.create(new ProducerRecord("foo", "bar"), null));
sender.send(sendMono)
	.then(sender.doOnProducer(producer -> {
		producer.flush();
		return Mono.empty();
	}))
	.subscribe();
Thread.sleep(1000);
sender.close();
```

While this "worked" with 1.2.4, it causes a deadlock with 1.3.0 - see https://issues.apache.org/jira/browse/KAFKA-10790

The deadlock is caused because the `flush()` is now called on the network I/O thread; it is waiting for the flush to be completed by the network thread (itself), which will never happen. With 1.2.4, it was scheduled and thus didn't block the I/O thread. With the 1.3 refactoring it is now called on the I/O thread.

Further more, `close()` on this producer blocks, awaiting a `join` on the network thread.

Examining this further, I said "worked" on 1.2.4, in that the code completed ok without deadlocking, but it actually achieved nothing.
In the example above the send `Mono` is completed when a send result (callback on the I/O thread) is received.

Since we have received a send result, a flush is unnecessary since the record must have already been sent to the broker.

Clearly, the developer was misguided.

However, it might be possible that something could be built into the `KafkaSender` to flush the produce at the "end" (when the "last" record has been published).

I don't know reactor well enough to know whether something like this is possible (knowing that we are "at the end") or whether some other technique (e.g. periodic flushing between sends, or using back pressure to flush at the end of each chunk) would work.

Regardless, it makes no sense (to me) for users to call `flush()` in `doOnProducer()`.

Am I missing something?

**Comment by simonbasle** [comment]
This has been fixed in c791395

**Comment by simonbasle** [comment]
I don't know if that directly translates well into `KafkaSender`, but obviously in Reactor one choice for detecting we're "at then end" is to implement something hooked to the `onComplete` and `onError` signals. `.then(...)` operator is one choice when you're only concerned about `onComplete`.

What would be the immediate action item? I don't think there is any real way of preventing that sort of `flush()` calls, but maybe the documentation should have a warning?

**Comment by garyrussell** [comment]
What is the point of calling `flush()` here at all?

It's not needed, unless you have increased the producer property `linger.ms` from its default `0`; it's like Nagle's Algorithm in TCP.

And, if you have, then calling `flush()` on every send defeats the whole purpose of increasing `linger.ms`.

By the way, `flush()` is a blocking operation.

**Comment by simonbasle** [comment]
I'll defer to you, I think it's fine to document that `flush()` is not supported (since we're already listing a restrictive set of methods in the javadoc)

**Comment by garyrussell** [comment]
Sure; I guess if they really want to flush, they could add a `.publishOn(...)`.

**Comment by garyrussell** [comment]
Doh - I originated this issue; closing as invalid.
