### ISSUE TITLE
ReceiverOffset.commit() stops pipeline propagation?

### ISSUE THREAD

**Issue by peterfigure** [reactor/reactor-kafka#188]
## Motivation
It looks like ReceiverOffset.commit() returns a `Mono.empty<Void>()` (at least in some cases?). For some reason this stops the pipeline even if it's composed with a map, eg:

```
    Mono.empty<Int>()
        .doOnTerminate { println("empty terminated") }
        .map {
            println("mapping empty")
            3
        }
        .subscribe { println("results!") }
```
The `.map{}` will never be executed, nor will the subscribe handler be executed. This can be problematic when there are tasks that depend on the receiver offset being committed eg (using with Kotlin Flow):

```
   kafkaFlow()
        .onEach {
            persistInitialContractState(it)
        }
        .flatMapConcat {
            receiverRecord.receiverOffset().commit().map { it }.asFlow() 
        }
        .map {
           markContractAsProcessed(it)
        }
        .collect { persistenceResult -> ... } 
```

## Desired solution
Is it possible to return something? Perhaps `Mono.just(commitOffset)` or otherwise -1 if nothing was available?

**Comment by bsideup** [comment]
Hi @peterfigure,

You should not be using `map` for side effects. There is nothing to return from `commit`, hence `Mono<Void>`.

Consider either using `Mono#doOnSuccess` or `Mono#then(Mono)`.

**Comment by peterfigure** [comment]
Hi @bsideup - thanks, `.then` solved my scenario nicely. 

I am curious though about your comment about `map` and side effects? What is the preferred way of creating side effects?
