### ISSUE TITLE
Kafka reactor v1.3.x is incompatible with Spring Boot 2.3.8.RELEASE (reactor-core 3.3.13.RELEASE)

### ISSUE THREAD

**Issue by vsethi13** [reactor/reactor-kafka#189]
Hello awesome folks at Kafka

I recently upgraded my spring boot dependencies from 2.2.7.RELEASE to 2.3.8.RELEASE while using kafka-reactor v1.2.2.RELEASE. It worked just fine. But as soon as I upgraded my kafka-reactor version to 1.3.x, I got an error and my application failed to start. The error went like this:

```
Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [reactor.kafka.sender.KafkaSender]: Factory method 'myAwesomeKafkaProducer' threw exception; nested exception is java.lang.NoClassDefFoundError: reactor/core/publisher/Sinks$EmitFailureHandler
```

I snooped around and found that the class ` reactor/core/publisher/Sinks$EmitFailureHandler` is actually missing as part of reactor-core v3.3.13.RELEASE.

**Comment by simonbasle** [comment]
Yes, `reactor-kafka` 1.3.0 is quite an extensive rework, intended to integrate with the `2020.0.x` release train / BOM, and `Spring Boot 2.3.x` uses the `Dysprosium` BOM (one cycle older). `Spring Boot 2.4.x` will embed the 2020.0 BOM
