### ISSUE TITLE
How to do graceful shutdown in reactive kafka consumer?

### ISSUE THREAD

**Issue by architmmmec** [reactor/reactor-kafka#196]
How to do graceful shutdown in reactive kafka consumer?

**Comment by simonbasle** [comment]
As far as I can see, the `KafkaReceiver` automatically closes the underlying kafka `Consumer`: the `ConsumerHandler` `close()` stops the `ConsumerEventLoop` which triggers a `CloseEvent` that shuts down the kafka `Consumer` here: https://github.com/reactor/reactor-kafka/blob/master/src/main/java/reactor/kafka/receiver/internals/ConsumerEventLoop.java#L371
