### ISSUE TITLE
How can I create a cold publisher that only emits when a subscription is created from another application?

### ISSUE THREAD

**Issue by tvergilio** [reactor/reactor-kafka#20]
Is it possible to create a Kafka publisher without subscribing to it, then, from another application, create a consumer, subscribe to the topic, and trigger the emission of records?

I am creating a publisher by:
1. calling `KafkaSender.create(senderOptions)`
2. followed by `createOutbound()`
3. followed by a succession of calls to `send()` for as long as the application is running.

On the consumer side (a different application), what I do is:
1. call `KafkaReceiver.create(options)`
2. followed by  `receive()`
3. followed by `subscribe(function -> doSomething())`

At the moment, the consumer receives nothing unless I do a `then().subscribe()` on the publisher, which makes it emit straight away. Ideally, I would like it to start emitting when the consumer from the other application subscribes.

Could you please advise me on whether what I am trying to do is feasible?

Many thanks.

**Comment by ilayaperumalg** [comment]
Hi @tvergilio ,

This requirement is more of the application side(controlling the publisher of one JVM from the condition from the other JVM) than the reactive side as the KafkaSender and KafkaReceiver are running on their own publisher/subscriber in their JVMs.

You might still control this by setting up some conditional subscriber on the KafkaSender's JVM which conditionally defer the `subscriber` based on some event received from the KafkaReceiver's JVM.

The `KafkaSender` is expected to be configured with the `subscribe` to start the KafkaProducer to send messages to the configured topic(s) within its own publisher/subscriber in its JVM.

**Comment by tvergilio** [comment]
Thank you very much for your suggestion. It is a shame that Project Reactor doesn't yet offer ready-made abstractions to deal with hot/cold observables, as does RxJava (http://reactivex.io/documentation/observable.html). So you are suggesting I implement a conditional subscriber on the Publisher that is triggered by an external subscription?  I was wondering if you could possibly show me a very simple example of how  you would implement this. Many thanks!

**Comment by smaldini** [comment]
Not sure what that question was but we actually have hot/cold publishers. From what i read you are interested in publish() operator, like in Rx it returns a ConnectableFlux you can use to start the subscription at the time you wish.
