### ISSUE TITLE
Kafka receiver  terminates flux with CommitFailedException after sometime and does not handle back-pressure

### ISSUE THREAD

**Issue by pavanpkp33** [reactor/reactor-kafka#218]
Hi @garyrussell / @simonbasle  ,

Following up on #190 , I updated my jar to version `1.3.3` but looks like I'm ending up with the same issue.

My situation : I have a high traffic kafka topic with messages being dumped at ~450 / sec and have couple of pods whose poll records is set to 3 and the following configuration for consumer props. 
```
{
  "fetch.max.wait.ms": 1000,
  "request.timeout.ms": 30000,
  "heartbeat.interval.ms": 3000,
  "session.timeout.ms": 10000,
  "auto.offset.reset": "latest",
  "connections.max.idle.ms": 540000,
  "max.poll.records": 3,
  "max.poll.interval.ms": 3000,
  "max.partition.fetch.bytes": 5048576
}
```   

I've truncated the rest of the properties. From the above properties, I see that my consumers run fine for ~ 25 minutes consuming messages at a set pace but after 25 mins, they die with the following exception. Also, my consumers take ~ 500 ms to process each record. Im running performance tests so the process time is standard.   

```
org.apache.kafka.clients.consumer.CommitFailedException: Offset commit cannot be completed since the consumer is not part of an active group for auto partition assignment; it is likely that the consumer was kicked out of the group.
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.sendOffsetCommitRequest(ConsumerCoordinator.java:1134)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.doCommitOffsetsAsync(ConsumerCoordinator.java:952)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsAsync(ConsumerCoordinator.java:919)
```

`Method = Operator called default onErrorDropped`.

My expectation- Consumer should not be kicked out of the group if backpressure is working as expected and it should send out empty polls. 

Other question - If a consumer gets terminated and disposed with this exception, how do I recover? My code is below.

```  
return receiver
        .receiveAutoAck()
        .onErrorContinue(
            (throwable, r) ->
                LOG.info(
                    null,
                    "Error while receiving messages",
                    "KF_ERROR",
                    throwable.getCause().toString()))
        .flatMap(
            consumerRecordFlux -> processFluxStream(consumerRecordFlux),
            jobConfiguration.getConsumerParallelPower())
        .onErrorContinue(
                     (throwable, o) -> {
              ConsumerRecord rec = null;
              if (o instanceof ConsumerRecord) {
                rec = (ConsumerRecord) o;
                dlqManager.publishToDLQ(rec, rec.topic());
              } else {
                dlqManager.publishToDLQ(o, jobConfiguration.getConsumerSource());
              }
              log.error(
                  "Error while processing record. [error={}, record={}]", throwable.toString(), o);
            })
        .retryWhen(Retry.backoff(3, Duration.ofMillis(500)))
        .subscribe();   
```
Thanks in advance.

**Comment by garyrussell** [comment]
It means you are holding up the consumer thread; you need to add a `.publishOn()` - see the test case...

https://github.com/reactor/reactor-kafka/blob/b1be003db976b3a91318ac1b2503f121d360c99e/src/test/java/reactor/kafka/receiver/KafkaReceiverTest.java#L1202

That will allow the consumer thread to keep polling. However, your `max.poll.interval.ms` is rather small.

Add `.repeat()` before the `.subcribe()` to start over after an error. Example here https://github.com/reactor/reactor-kafka/issues/214#issuecomment-821433026

**Comment by pavanpkp33** [comment]
Thanks, @garyrussell . Will try it out. Much appreciated.

**Comment by simonbasle** [comment]
to clarify @garyrussell's comment, it's not `repeat` but `retry` that re-subscribes in case of `onError` termination, so favor that ;)

**Comment by m-mansoor-ali** [comment]
Hi @pavanpkp33 , did @garyrussell's comment help you solve this issue? 
I am facing the same issue, I have a high traffic kafka topic that gets populated by a scheduler with 150,000+ messages at noon everyday. The consumers start consuming messages just fine, but then I see duplicate message consumption and eventually no message consumption at all. Here's how I am consuming the messages.
`
fetchBillRequestsKafkaConsumerTemplate
        .receiveAutoAck()
        .doOnNext(consumerRecord -> log.info("received key={}, value={} from topic={}, offset={}",
            consumerRecord.key(),
            consumerRecord.value(),
            consumerRecord.topic(),
            consumerRecord.offset())
        )
        .map(ConsumerRecord::value)
        .map(UUID::fromString)
        .flatMap(accountId -> accountRepository.findById(accountId))
        .flatMap(userAccount -> reminderService.createReminder(userAccount))
        .flatMap(reminder -> notificationService.sendPushNotification(reminder))
        .doOnError(throwable -> log.error("An error occurred while consuming kafka message", throwable))
        .subscribeOn(Schedulers.elastic()).subscribe();
`

**Comment by pavanpkp33** [comment]
@m-mansoor-ali  - Yes, @garyrussell 's suggestion worked for me. I publish messages now on a scheduler and do a `retry()`  to recover from errors.
