### ISSUE TITLE
Out of memory in ConsumerEventLoop after rebalance

### ISSUE THREAD

**Issue by koldat** [reactor/reactor-kafka#237]
We are having out of memory issues when there is a rebalance and there is a lot of messages in Kafka. ConsumerEventLoop is simply looking like it is not paused on backpressure. I have a memory dump so I have a proof it does not work as expected.

I think the issue is that consumerEventLoop is not doing any action on "rebalance" so what happens:
1. Flux is full -> pause, pausedByUs =true, TopicPartitionsState pause = true
2. Rebalance happens (here Kafka Client resets TopicPartitionsState pause = false, because there is different set of partitions)
3. poll happens, but because we are already "pausedByUs == true", we do not pause new partitions.
4. It polls into sink until we are OOM

Evidence:

1. All TopicPartitionsState are "false" (not paused):
![image](https://user-images.githubusercontent.com/16866502/131475224-b0d8d455-8105-4006-9821-6c09b7eeb3b2.png)

2. consumerEventLoop requested is 0 and pausedByUs is TRUE. This means TopicPartitionsState pause must be "true", but it is not:
https://github.com/reactor/reactor-kafka/blob/6d9379a4930a5fe19e4d7baad2860b7627a78a6c/src/main/java/reactor/kafka/receiver/internals/ConsumerEventLoop.java#L282
![image](https://user-images.githubusercontent.com/16866502/131475494-716bfd57-1c40-4008-8c6a-9bbb17aede6a.png)

3. sink is very full (almost 60k messages):
![image](https://user-images.githubusercontent.com/16866502/131475623-25bb8441-5009-4b74-bd52-43ece68c53aa.png)

## Expected Behavior
Backpressure with very basic used case should work:

```java
        KafkaReceiver<String, ServicesKafkaMessage> receiver = createReceiver(owner);
        Flux<ReceiverRecord<String, ServicesKafkaMessage>> messages = receiver.receive();
        messages
            .flatMap(v -> processMessage(v)))
            .blockLast();
```

## Actual Behavior
There is OOM when rebalance happens and kafka is paused (some new instance is started remotely for example).

## Steps to Reproduce
1. Have blocked Flux (slow)
2. Rebalance
3. Keep having new messages

## Possible Solution
We should reset pausedByUs in case of rebalance.

## Your Environment
Spring Boot 2.5.3
Kafka Reactor 1.3.4

**Comment by koldat** [comment]
This issue is related to change that leads to this situation: #183

**Comment by garyrussell** [comment]
Yes; we need to re-pause after a rebalance.

**Comment by koldat** [comment]
Thank you. Do you want me to help you somehow? This is kind of important as it can kill our service any time. I do not think this was happening before we had upgraded to latest Spring Boot. I am not sure what can be workaround for it. Please keep me posted if you see it can be fixed in near future so I can potentially come up with some workaround (like downgrade).

**Comment by garyrussell** [comment]
I am not aware of any change that would cause this behavior since we first fixed back pressure support (1.3.3) - the only change since then was to wake the consumer to speed up resuming after the backpressure is released (and that's not released yet).

I will take a look at this this soon.

**Comment by koldat** [comment]
I have meant this 6 months old change (partition change): 9fddabbc1772830fabd814bc00cca4daddd04759

**Comment by garyrussell** [comment]
Ah; thanks, yes that broke it - the previous code kept re-pausing on every loop iteration.

However, back-pressure didn't work properly at all before 1.3.3.

I have submitted a PR to correct the problem.

**Comment by koldat** [comment]
@garyrussell That was very fast. Fix looks good to me. Thank you!

I am not pushing, but can I ask please what could be reasonable date of having this fix released? Our release is coming as well and I need to know how to handle this issue on our side.

**Comment by garyrussell** [comment]
It looks like the next reactor releases are scheduled for Sept 14.

cc/ @simonbasle

**Comment by simonbasle** [comment]
Yes, next round of releases is scheduled on September 12, will have a look
at the pr early next week when I'm back if it isn't reviewed and merged by
then.

**Comment by koldat** [comment]
Thank you both. This date sounds perfect for us.

**Comment by koldat** [comment]
@simonbasle Tomorrow is releases scheduled, but I do not see PR merged. Is it still on the plan?

**Comment by simonbasle** [comment]
Thanks for the reminder, will merge. Can you test the snapshot once the build is green @koldat ?

**Comment by koldat** [comment]
Yes I can test it.

**Comment by simonbasle** [comment]
merged 👍 watch https://github.com/reactor/reactor-kafka/actions/runs/1228793476

**Comment by koldat** [comment]
@simonbasle I have tested 1.3.6-SNAPSHOT and it works as expected
