### ISSUE TITLE
How to implement retry and recover logic with Reactive Kafka

### ISSUE THREAD

**Issue by saurabh01018** [reactor/reactor-kafka#242]

**Comment by simonbasle** [comment]
generic questions like this are best answered on [StackOverflow](https://stackoverflow.com/questions/tagged/project-reactor) or on [Gitter](https://gitter.im/reactor/reactor?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

![image](https://user-images.githubusercontent.com/6986166/134325712-8aac8060-7a8a-4f06-998c-9340961bf1a2.png)

Be sure to flesh the question a bit more on these platforms.
