### ISSUE TITLE
Investigate the cause of a RejectedException while retrying kafka aknowledgement

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-kafka#245]
### Original comment by @Aniket-Singla

Hi @simonbasle , I am consuming messages in the following way:

```
redemptionEventReactiveKafkaConsumerTemplate
                .receiveAutoAck()
                .doOnNext(consumerRecord -> log.info("received key={}, value={} from topic={}, offset={}",
                        consumerRecord.key(),
                        consumerRecord.value(),
                        consumerRecord.topic(),
                        consumerRecord.offset())
                )
                .map(ConsumerRecord::value)
                .flatMap(this::consume)
                .onErrorContinue((error, value)->log.error("something bad happened while consuming : {}", error.getMessage()))
                .retry(4)
                .subscribe();
```
When kafka commit fails for the first time ( to creating this scenario, I am adding a breakpoint in the consume method):

```
org.apache.kafka.common.errors.DisconnectException: null

2021-09-28 15:16:39.830  WARN [cxinteracts-mp-member-offers,,,] 22812 --- [emption-event-2] r.k.r.internals.DefaultKafkaReceiver     : Commit failed

org.apache.kafka.clients.consumer.RetriableCommitFailedException: Offset commit failed with a retriable exception. You should retry committing the latest consumed offsets.
Caused by: org.apache.kafka.clients.consumer.internals.NoAvailableBrokersException: null

org.apache.kafka.clients.consumer.CommitFailedException: Offset commit cannot be completed since the consumer is not part of an active group for auto partition assignment; it is likely that the consumer was kicked out of the group.
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.sendOffsetCommitRequest(ConsumerCoordinator.java:1116) ~[kafka-clients-2.5.1.jar:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.doCommitOffsetsAsync(ConsumerCoordinator.java:936) ~[kafka-clients-2.5.1.jar:na]
Caused by: org.apache.kafka.clients.consumer.internals.NoAvailableBrokersException: null
```

It retries 4 times as per the code, but throws exception in each retry:

```
2021-09-28 15:16:39.917 ERROR [cxinteracts-mp-member-offers,,,] 22812 --- [     parallel-4] reactor.core.scheduler.Schedulers        : Scheduler worker in group main failed with an uncaught exception

reactor.core.Exceptions$StaticRejectedExecutionException: Scheduler unavailable

```

I am creating subscription in spring CommandLineRunner bean.

### @simonbasle wrote:

> I am creating subscription in spring CommandLineRunner bean.

I think that is the issue. Since you call `.subscribe()`, which is *non-blocking*, execution of the `CommandLineRunner` isn't waiting for actual kafka processing.

If there isn't any more code after that, the `CommandLineRunner` will terminate, and it is likely that means your app shuts downs and reactor default `Schedulers` get disposed as well at that point.

### @Aniket-Singla wrote:

CommandLineRunner does exits after running run method ( in the main thread ), but the app does not shut down.  Can you please suggest a better place to start subscription in spring application ? Or if anyone else using reactor-kafka with spring can share some leads that will be helpful.

### @simonbasle wrote:

 @Aniket-Singla unfortunately the `RejectedException` that you get is a singleton one, which doesn't give us much information as to which `Scheduler` was shut down.

 - A `Scheduler` is somehow in play in your reactive chain (might be the `Schedulers.immediate()` one which is used as "no-op" default by `KafkaReceiver` IIRC).
 - That `Scheduler` is somehow disposed at the point where a `retry` is attempted, even though it is potentially still used.
 - `Schedulers.immediate` would only be disposed by `Schedulers.shutdownNow()` call or `Schedulers.setFactory(f)` call

The `CommandLineRunner` was a prime suspect at something going amiss because of the non-blocking nature of Reactor vs the blocking nature of CLR.

Would you be able to debug, see what Reactor class calls `Exceptions.failWithRejected()` ? This may give us a hint at which `Scheduler` is rejecting tasks here.

**Comment by Aniket-Singla** [comment]
Hi @simonbasle ,

>Would you be able to debug, see what Reactor class calls Exceptions.failWithRejected() ? This may give us a hint at which Scheduler is rejecting tasks here.

The flow is as follows:
ExecutorServiceWorker#schedule(Runnable task) -> Schedulers#workerSchedule(exec, disposables, task, 0L, TimeUnit.MILLISECONDS) -> throw Exceptions.failWithRejected();

Let me know if any other thing is required in this regard.

**Comment by kharel** [comment]
@simonbasle it happened to me as well when I used acknowledge() and I did not add any scheduler from my side.
so I assumed that the exception is probably referring to scheduler in the reactive kafka itself.

**Comment by simonbasle** [comment]
@Aniket-Singla there is exactly [one place](https://github.com/reactor/reactor-kafka/blob/4155f6c5c0cea5559e24743f0d4a1754a970e69a/src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java#L138) where `SingleWorkerScheduler` is used in reactor-kafka.

This is the backing `withHandler` behind `receive()`/`receiveAutoAck`.

So that scheduler wraps a `Worker` from `receiverOptions.schedulerSupplier()`. It also disposes the worker once the `receive()` has completed.

Somehow, the error would indicate that that `Scheduler` is still used after that disposal.

I'm stumped. We'd really need a reproducer that can easily be set up without having to install and configure some Kafka instance (something that could be run as a typical reactor-kafka unit test, which means it would be possible for the reproducer to use testContainers).

The call tree that leads to `failWithRejected()`, I suspect, starts in one of the numerous `publishOn` used by `reactor-kafka`, so classic debug would lead you only to `FluxPublishOn`.

You'll need `Hooks.onOperatorDebug()` to be able to even get a sense of which part of `reactor-kafka` actually leads to that `execute` call. (see https://projectreactor.io/docs/core/release/reference/#debug-activate).

I'd also need to know what causes the disposal of the `SingleWorkerScheduler`, although I suspect it is the `Scheduler::dispose` method reference in `Flux.using` call [here](https://github.com/reactor/reactor-kafka/blob/4155f6c5c0cea5559e24743f0d4a1754a970e69a/src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java#L140).

So again, simple debug will lead you to the `FluxUsing` class, and you'd need `onOperatorDebug()` to find a trace back to reactor-kafka...

@Aniket-Singla can you confirm you have done 0 setup of `Scheduler` anywhere in the reactor-kafka configuration (eg. `receiverOptions.schedulerSupplier(Supplier)`)?

@kharel how did you use `acknowledge()` exactly? did you use `doAfterTerminate(...)` like what's done in `receiveAutoAck` by any chance? 

And you confirm that when you say "I didn't add any Scheduler" you include specifying schedulers in the reactor-kafka configuration (eg. `receiverOptions.schedulerSupplier(Supplier)`)?

**Comment by Aniket-Singla** [comment]
These are the configurations for receiverOptions:
```
@Bean
    public ReceiverOptions<String, Message<?>> receiverOptionsForMessageConsumer(KafkaProperties kafkaProperties) {
        Map<String, Object> props = getPropsForMessage(kafkaProperties);
        ReceiverOptions<String, Message<?>> receiverOptions = ReceiverOptions.create(props);
        return receiverOptions.subscription(Collections.singletonList(topicName));
    }

    @Bean
    public ReactiveKafkaConsumerTemplate<String, Message<?>>
    reactiveKafkaConsumerTemplate(KafkaProperties kafkaProperties) {
        return new ReactiveKafkaConsumerTemplate<>(receiverOptionsForMessageConsumer(kafkaProperties));
    }
```
I am using reactor-kafka in conjunction with spring-kafka, though I donot think using ReactiveKafkaConsumerTemplate, will try to use a different scheduler, I did check the template , it is just

```
public Flux<ConsumerRecord<K, V>> receiveAutoAck() {
		return this.kafkaReceiver.receiveAutoAck().concatMap(Function.identity());
	}
```

Regarding test-cases and Hooks.onOperatorDebug(), I will check that later as soon as I get time.

Just in case if required I am using the following versions:
1. reactor-kafka : 1.2.2.RELEASE
2. reactor-core: 3.3.17.RELEASE

**Comment by garyrussell** [comment]
The template is only a lightwieght wrapper.

There was major rework to reactor-kafka in 1.3.x; the current version is 1.3.6.

**Comment by Aniket-Singla** [comment]
Hi @garyrussell , @simonbasle , I can confirm, the issue does not exist on version 1.3.6 and can be closed, thanks for helping.

**Comment by simonbasle** [comment]
@kharel were you in the same situation, using reactor-kafka 1.2.x ?

**Comment by kharel** [comment]
@simonbasle I was using 1.3.4 when I encountered this issue
didn't try with 1.3.6

**Comment by kharel** [comment]
@simonbasle sorry disregard my last comment. I encountered this issue on 1.2.2

**Comment by simonbasle** [comment]
Got it, closing this then
