### ISSUE TITLE
Spring Cloud support - Specifically Spring Cloud Stream and Spring Cloud Function

### ISSUE THREAD

**Issue by roger751** [reactor/reactor-kafka#252]
## Documentation Issue

It's pretty unclear if that project is used if I'm using Spring Cloud Stream with Kafka Binder. I know that there is a Spring Cloud Stream support for Kafka and for Reactive programming with project reactor. I also know that `spring-cloud-stream-reactive` is discontinued and no longer distributed in favor of native support via spring-cloud-function. I want to understand what is exactly the alternative for reactor-kafka in Spring Cloud Stream and Spring Cloud Function. [This issue](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/1075) specify that there was an intention of using the Reactor Kafka with Spring, but as for my understanding it has not been done. It's unclear for a Spring user to understand what is the most recommended way of consuming from Kafka with Reactor Kafka, but still use the Spring Cloud ecosystem (e.g. Spring Cloud Function, Spring Cloud Config, ideally Spring Cloud Stream if it was possible and more).

## Improvement Suggestion

Some sections of explaining what's happening. Its very hard to work on big projects when there are so many unconnected dependencies. A place of explanation to the "dumb" user that wants to reactively consume from Kafka with Spring Cloud, using Reactor Kafka.

## Additional context

If the recommended way is not to use Reactor Kafka, does Spring provides alternatives of their own for all of the Reactive features that was implemented here? Do they have reactive error handlings, sophisticated commits mechanism and more of their own?

**Comment by garyrussell** [comment]
The recommended way **will be** to use reactor-kafka, but it needs work in `spring-cloud-stream` to create a binder for it; it has just not been resourced yet.

Contributions are welcome.

**Comment by roger751** [comment]
Ok. But what is the current recommended way? Is it currently even possible to use Spring Cloud Function with reactor kafka (to give up on Spring Cloud Stream until the whole binding thing will be implemented)?

Or would you rather go with the Spring Cloud Stream & its Kafka Binder and let them do the kafka consumption (what you still do it if your application is reactive?)?

And also - in case you happen to know - how does Spring Cloud Stream Kafka Binder consume from kafka reactively? Spring-Kafka async usage or some implementation of its own?

**Comment by garyrussell** [comment]
>But what is the current recommended way?

There is none (until the new binder is created); using reactor on a non-reactive binder is not recommended at all (but see below).

>how does Spring Cloud Stream Kafka Binder consume from kafka reactively

it doesn't; they should never have added reactor support there until they had a reactive binder.

That said, because spring-kafka 2.8 now [supports out of order manual commits](https://docs.spring.io/spring-kafka/docs/current/reference/html/#x28-ooo-commits) and it will pause (back pressures) the consumer between polls until all "missing" offsets are committed for the results of the last poll, it is now safer to add reactor on top of the listener container.

The latest spring-cloud-stream uses 2.8.

Just set the `ackMode` to MANUAL or MANUAL_IMMEDIATE and use the `Acknowledgment` header to commit the offset; if it is out of order, it will be deferred until the gap(s) are filled.

I am adding a similar mechanism to reactor-kafka [soon](https://github.com/reactor/reactor-kafka/issues/243#issuecomment-987113530); even this project doesn't handle out of order commits currently.

**Comment by roger751** [comment]
Sounds great. I'm also interested in your opinion about the solution that you've suggested in comparison to @artembilan's [suggestion of using reactor kafka to pass a flux into a Spring Integration endpoint?](https://github.com/spring-cloud/spring-cloud-function/issues/779#issuecomment-987310634)

**Comment by artembilan** [comment]
@roger751 , what Gary is doing here has nothing to do with Spring Integration channel adapter.
You don't compare apples with apples. 
The low-level solution is indeed reactor-kafka. 
Then it could be a listener container in the Spring for Apache Kafka on top of this reactive `KafkaReceiver`.
In addition to that we can implement Spring Integration channel adapter on top of the same `KafkaReceiver`.

**Comment by garyrussell** [comment]
Closing this since it is spring-cloud-stream related; any follow-ups should be on https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/1075

**Comment by almogtavor** [comment]
> because spring-kafka 2.8 now [supports out of order manual commits](https://docs.spring.io/spring-kafka/docs/current/reference/html/#x28-ooo-commits) and it will pause (back pressures) the consumer between polls until all "missing" offsets are committed for the results of the last poll, it is now safer to add reactor on top of the listener container.

@garyrussell do you suggest here using the asynchronous Spring-Kafka consume option (with ooo commits) to produce a flux that my application will process with reactive? So that there will be one thread that reads asynchronously and a thread pool that will process the messages with reactive?

**Comment by garyrussell** [comment]
The PR for OOCs in this project is ready for review https://github.com/reactor/reactor-kafka/pull/253

If you can't wait for that to be merged, you might get some inspiration from a reactive adapter I started working on for the listener container some time ago; I decided not to merge it though. It used a parallel scheduler to process records emitted by the consumer thread.

https://github.com/spring-projects/spring-kafka/pull/1941
