### ISSUE TITLE
Consumer gets stuck after a rebalance when using out of order commits

### ISSUE THREAD

**Issue by pdanelson** [reactor/reactor-kafka#259]
A consumer rebalance, eg. a consumer leaving a multi consumer group, may trigger the remaining consumers to have an ever increasing deferred commit count which eventually leads to an indefinitely paused consumer if using the out of order commits feature.

## Expected Behavior

Consumer should continue consuming events and committing even after a rebalance.

## Actual Behavior

After a rebalance, the deferred commit count starts increasing until it reaches the max deferred commits limit at which point the consumer pauses and never recovers.

## Steps to Reproduce

```java
@Test
void reproCase() {
    var consumerProps = Map.<String, Object>of(
        ConsumerConfig.GROUP_ID_CONFIG, TEST_TOPIC,
        ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, getKafkaServer(),
        ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest"
    );
    var consumerOpts = ReceiverOptions.<String, String>create(consumerProps)
        .commitInterval(Duration.ofSeconds(2L))
        .maxDeferredCommits(1000) // Just to demonstrate that consumer pauses and never recovers, the deferred count itself would grow unbounded
        .withKeyDeserializer(new StringDeserializer())
        .withValueDeserializer(new StringDeserializer())
        .subscription(Collections.singleton(TEST_TOPIC)); // Test topic should have 2+ partitions

    var subscription1 = KafkaReceiver.create(consumerOpts)
        .receive()
        .subscribe();
    
    var subscription2 = KafkaReceiver.create(consumerOpts)
        .receive()
        .flatMap(record -> Mono.delay(Duration.ofMillis(100L * RandomUtils.nextInt(1, 5))) // Simulate async event processing
                .doOnSuccess(__ -> record.receiverOffset().acknowledge()),
            10)
        .subscribe();
    
    Thread.sleep(20_000L); // Deferred count stays consistently in the single digits during this period
    subscription1.dispose(); // Force a re-balance
    
    Thread.sleep(100_000L); // Deferred count starts to grow until it maxes out the deferred commits limit during this period
    subscription2.dispose();
}
```

## Possible Solution

The issue seems to be caused by the offset lists in `CommitableBatch.uncommitted` becoming unsorted after a re-balance that assigns to a consumer the same partitions that had previously been revoked from that consumer. This is because the first poll after a re-balance will retrieve duplicates of the events that were previously retrieved, but not yet committed.

A potential fix would be to sort those lists similar to what is already done with the deferred commits lists, eg.
```java
    public synchronized CommitArgs getAndClearOffsets() {
    ...
        if (this.outOfOrderCommits) {
            this.deferred.forEach((tp, offsets) -> {
                if (offsets.size() > 0) {
                    Collections.sort(offsets);
                    List<Long> uncomittedThisPart = this.uncommitted.get(tp);
                    Collections.sort(uncomittedThisPart); // Fix
                    long lastThisPart = -1;
                    while (offsets.size() > 0 && offsets.get(0).equals(uncomittedThisPart.get(0))) {
                        uncomittedThisPart.remove(0);
                        lastThisPart = offsets.get(0);
                        offsets.remove(0);
                    }
                    if (lastThisPart >= 0) {
                        offsetMap.put(tp, new OffsetAndMetadata(lastThisPart + 1));
                    }
                }
            });
            batchSize = deferredCount();
        }
    ...
    }
```

## Your Environment

* Reactor version(s) used: 1.3.8
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`): 17
* OS and version (eg `uname -a`):

**Comment by rancherz** [comment]
@garyrussell Look right. What do you think? This is a pretty serious problem

**Comment by garyrussell** [comment]
Yes, this is a valid issue.

**Comment by garyrussell** [comment]
I don't think we can simply sort the deferred commits; we probably need some kind of epoch and reject any commits of deferred offsets from the last epoch (prior to the rebalance).

**Comment by aebruikeraebruiker** [comment]
Will there be a fix soon?

**Comment by garyrussell** [comment]
I just submitted a pull request.
