### ISSUE TITLE
Consumer stops after rebalance

### ISSUE THREAD

**Issue by micr0farad** [reactor/reactor-kafka#264]
Hey! I have an issue after consumer group rebalance resulting in all partitions being assigned to single consumer. I use the following stream:
```java
    Scheduler messageHandlingScheduler = Schedulers.newBoundedElastic(
        100,
         Integer.MAX_VALUE,
         "messageHandlingScheduler",
         60,
         true
    );
    ReceiverOptions<String, GenericRecord> receiverOptions = ReceiverOptions.<String, GenericRecord>create(config)
            .maxDeferredCommits(100)
            .addAssignListener(p -> log.info("Partitions assigned {}", p))
            .addRevokeListener(p -> log.warn("Partitions revoked {}", p))
            .subscription(List.of("my-topic"));

    KafkaReceiver.create(factory, receiverOptions)
          .receive()
          .subscribeOn(messageHandlingScheduler)
          .publishOn(messageHandlingScheduler)
          .cancelOn(messageHandlingScheduler)
          .groupBy(ReceiverRecord::key, Integer.MAX_VALUE)
          .flatMap(
              group -> group.take(Duration.ofHours(2), messageHandlingScheduler)
                  .onBackpressureBuffer(Integer.MAX_VALUE)
                  .subscribeOn(messageHandlingScheduler)
                  .publishOn(messageHandlingScheduler)
                  .cancelOn(messageHandlingScheduler)
                  .flatMapSequential(
                      message -> Mono.fromRunnable(() -> /*handle message synchronously*/ {})
                          .doOnSuccess(v -> commit(message))
                          .doOnError(error -> {
                              commit(message);
                              // handle error synchronously
                          })
                          .onErrorResume(t -> Mono.empty()),
                      Integer.MAX_VALUE,
                      Integer.MAX_VALUE
                  ),
              Integer.MAX_VALUE,
              Integer.MAX_VALUE
          )
          .onErrorContinue((e, o) -> logFatalError(e))
          .subscribe();
```

Right after partition assignment stream no longer emits messages and does not provide any exceptions. 
I'm not sure it's a 100% bug but it's pretty hard to understand what is the root cause. I'd be happy to provide a PR if someone get a clue of what's exactly happening here.

**Comment by garyrussell** [comment]
Try adding `.repeat()`. See https://github.com/reactor/reactor-kafka/issues/214#issuecomment-851416437

**Comment by micr0farad** [comment]
@garyrussell thanks for the reference. I've added `.repeat()` right before subscribe and `retryWhen(Retry.backoff(3, Duration.of(10L, ChronoUnit.SECONDS)))` for commit Mono and it solved my issue. 
Closing this issue as no fix required.

**Comment by almogtavor** [comment]
@garyrussell does this appear in the docs?

**Comment by garyrussell** [comment]
It appears not; reopening as a doc issue.

**Comment by flavium31** [comment]
I'm happy to raise a PR for this. Should we have an Error handling section under Reactive Kafka Receiver  (just like we have for the sender) to describe this or just update the [sample snippet](https://projectreactor.io/docs/kafka/release/reference/#kafka-source)? WDYT @garyrussell ?

**Comment by garyrussell** [comment]
Thanks for the offer - we should probably do both.

**Comment by AcevedoR** [comment]
Hello, any updates regarding the documentation PR #284 ?
As a newbie user I found it useful, I actually encountered a similar issue that could have been avoided with this doc.

**Comment by garyrussell** [comment]
Closed by https://github.com/reactor/reactor-kafka/commit/f74cd96460b3b069917b82ed96580edfb0090ebd

Sorry for the delay.
