### ISSUE TITLE
Publish a tests dependency for Reactor Kafka

### ISSUE THREAD

**Issue by migroskub** [reactor/reactor-kafka#269]
## Motivation

I want to write tests for a project of mine that uses Reactor Kafka, and I'd like to use the classes that this project had made for its own tests that easily let me mock the needed class and get the needed environment (especially `AbstractKafkaTest`).

## Desired solution

Publish a `reactor-kafka-1.3.10-tests.jar` jar file to [Maven Central](https://repo1.maven.org/maven2/io/projectreactor/kafka/reactor-kafka/1.3.10/).

## Additional context

https://github.com/reactor/reactor-kafka/blob/main/src/test/java/reactor/kafka/AbstractKafkaTest.java

**Comment by garyrussell** [comment]
Understandable request, but I don't think we would want to guarantee non-breaking changes in these classes, even within point releases; it would add quite a bit of a maintenance burden to do that.

**Comment by migroskub** [comment]
Why not? That can only help people. You can just keep the release branches if the changes are major, so people will be able to see the state of these classes in each release.

**Comment by apffa** [comment]
I'd also like that to be published

**Comment by simonbasle** [comment]
These are not general-purpose test-supporting classes (like assertions or the like), but rather setting up a _test environment_, using assumptions and configuration that matches the test infrastructure of Reactor-Kafka.

While it is a fine idea to take inspiration from this and copy that model over in your own projects, we cannot pretend these assumptions and configurations will fit _any_ project.

And as Gary said, we cannot commit to the fact that a whole maintenance branch will never need changes to these configurations either, which - if shared - would break downstream users.

This is a hard no from my perspective.
