### ISSUE TITLE
Bad commit Offset 

### ISSUE THREAD

**Issue by YohanAlard** [reactor/reactor-kafka#278]
I had a difference in commit offset between a logstash consumer and a kafka reactor (ReceiverOffset) even if there is no logic in the code. What i see in reactor implementation, the commit offset is the last read offset +1. 

Unfortunately, my producer (a kafkastream application) provide a "missing offset" at the end of the processing stream (i don't know why) and so always i have a lag of 1 in reactor implementation (producer - consumer offset)

I was thinking it was a producer error but other client (like a logstash) provide the good commit offset (next producer offset) 

## Expected Behavior
I expect reactor kafka to commit the next available offset for the producer) and not the last commit +1.

## Actual Behavior
Last read offfset +1 is commited.

**Comment by garyrussell** [comment]
I assume you are using transactions so the false lag is due to that; perhaps your logstash producer is not using transactions?

See https://issues.apache.org/jira/browse/KAFKA-10683

**Comment by YohanAlard** [comment]
Hi @garyrussell, you assume very well. My kafkastream application is transactional. 
the logstash is also a consumer (in fact, i m hopping that our reactive consumer will replace it but we need to solve the lag computation first).
Is there a plan for kafka reactor to handle it this case ?

**Comment by garyrussell** [comment]
As you can see on the JIRA I referenced, it is not a problem with reactor-kafka; the problem is with Kafka itself; as you can see in the comments there, the suggested work around does not work for all cases (and it adds overhead to every  offset commit). We therefore have no plans to try and mask their bug here.

I suggest you lobby for a fix over there.

**Comment by YohanAlard** [comment]
I totaly agree, thank you for your help.
