### ISSUE TITLE
Improve acknowledgement throughput when utilising deferred commits under high load

### ISSUE THREAD

**Issue by pdanelson** [reactor/reactor-kafka#299]
## Motivation

Currently acknowledgement time for a record grows linearly with the sizes of the uncommitted and deferred offsets queues due to them being implemented as linked lists which need to be checked for the presence of the offset for each acknowledgement. This can become a throughput bottleneck for high load workloads, especially since acknowledgement is a [synchronized method](https://github.com/reactor/reactor-kafka/blob/86d545613fbcb005587693a8b310d3581cb62fd7/src/main/java/reactor/kafka/receiver/internals/CommittableBatch.java#L48) and thus can not be invoked concurrently from multiple threads.

For example, based on a quick benchmark on my own machine, a deferred commit queue size of 100 000 records would already cap the throughput of the consumer to a maximum 3 000 records per second as the contains check of the linked list alone would take ~0.3 milliseconds for each acknowledgement.

<img width="737" alt="Screenshot 2022-10-19 at 21 31 40" src="https://user-images.githubusercontent.com/19771958/196782339-3ea73dc0-6e27-4467-bd51-509920172916.png">

## Desired solution

Based on the logic that the deferred and uncommitted offsets queues already get cleared [when partitions are revoked](https://github.com/reactor/reactor-kafka/blob/86d545613fbcb005587693a8b310d3581cb62fd7/src/main/java/reactor/kafka/receiver/internals/CommittableBatch.java#L94), there should(?) not be any possibility of duplicate offsets and it should be possible to remove the expensive checks for element presence and make the acknowledgement an effectively constant time operation.

**NB!** If the above assumption about duplicates is wrong then I would expect that there might be a bug present in the feature regarding draining the pipeline before rebalancing as the records in pipeline counter is incremented for every polled record (no duplicate offset check), but decremented only if the acknowledgement is not a duplicate.

## Considered alternatives

In case there is another edge case where duplicate offsets may occur and the presence checks can not be removed, replacing the linked list based implementation with a tree set based implementation would at least make the acknowledgments scale logarithmically not linearly with the queue sizes (while also maintaining offsets in order and not requiring an explicit sort when [committing](https://github.com/reactor/reactor-kafka/blob/86d545613fbcb005587693a8b310d3581cb62fd7/src/main/java/reactor/kafka/receiver/internals/CommittableBatch.java#L118)) the offsets.

## Additional context

Our workload is a highly concurrent one where we split records from each partition into hundreds of parallel rails, each of which can be temporarily delayed due to transient network issues while the rest of the rails continue consumption, thus temporarily creating high numbers of deferred commits. Those transient issues tend to end up being distributed uniformly across the parallel rails and we are not overly concerned about duplicate consumption, so we prefer to keep a high deferred commits ceiling to avoid consumer pauses in favour of higher throughput. Currently, this can become problematic though, since high numbers of deferred commits will make us hit the throughput bottleneck that is hard to recover from.

**Comment by garyrussell** [comment]
Thanks for the analysis, it wasn’t expected that there would be such a large number of deferred commits. Feel free to submit a PR with suggested performance improvements.

**Comment by pdanelson** [comment]
Ack. Will read through the contributor guidelines and open a PR shortly.
