### ISSUE TITLE
Add Option to Pause All After Rebalance

### ISSUE THREAD

**Issue by garyrussell** [reactor/reactor-kafka#307]
Something like `receiverOptions.pauseAllAfterRebalance(true)`.

When true, pause all partitions on assignment after rebalance, if **any** partitions were paused before the rebalance.

See https://stackoverflow.com/questions/74497869/reactor-kafka-how-to-gracefully-shutdown#comment132042723_74497869

Also add pause method to `ReceiverPartition`.

**Comment by axiopisty** [comment]
Hi, I found this issue from reading the StackOverlfow question you mentioned in this issues description.

The title of that StackOverflow question indicates that the requested feature is to enable "Graceful Shutdown" of the Reactive Kafka Consumer. I'm experiencing the same problem where the application I'm working on won't shut down without either having to manually kill the process, or forcefully interrupting the consumer thread and then getting exception logs.

As you requested in that StackOverflow thread, I have created a MCRE along with a README file that demonstrates the issue as I'm experiencing it. Maybe I'm just doing something wrong? I hope this example is helpful.

https://github.com/axiopisty/reactive-kafka-consumer-shutdown-demo

**Comment by garyrussell** [comment]
That question title is misleading; this issue was the result of a follow on comment; it has nothing to do with graceful shutdown.

Thanks for providing an MCRE, I will look at it when I return after the holidays, but it would be better to open a new issue since it is unrelated to this one.

**Comment by axiopisty** [comment]
Thank you for your response. Preparing an MCRE is valuable for so many reasons. While they do help maintainers to understand/reproduce/test issues, they also help give clarity to the creator of the MCRE. It occurred to me yesterday after preparing this that I was probably missing something. After dwelling on it in my sleep last night, I woke up this morning to test "disposing" of the subscription. Sure enough, the application is shutting down gracefully now!

I've pushed a final commit to the repository referenced above containing the fix to the problem I was experiencing. I'm tempted to remove the project and my comments from this thread. But I think I'll leave them there for a little while.

There's no need for you to review the project if you don't want to Gary. Merry Christmas!

**Comment by andy-vegeta** [comment]
@axiopisty does your sample wait for current processing message to finish before disposing the subscription?

**Comment by Gin2022Null** [comment]
@garyrussell Any ETA about this feature will be included in a future release? Thanks!

**Comment by garyrussell** [comment]
I don't currently have an ETA; contributions are welcome.

**Comment by Gin2022Null** [comment]
Just created a pull request for this enhancement.
