### ISSUE TITLE
Remove invasive error-logging in DefaultKafkaSender / SendProducer.java

### ISSUE THREAD

**Issue by kotlinlukas** [reactor/reactor-kafka#309]
## Motivation
The DefaultKafkaSender fails with an error in console, if i.e. the record that we plan to send is too large (as intended).
However, when we catch and handle that error in our logic, we notice that the original error is still logged to the console as error, despite being caught and handled in our application logic.
This is causing problems for our logging and monitoring which notices errors in our log output, despite the fact that the application has not crashed and is handling the error just fine.

After some investigation, we noticed that the reason for this is the log.error statement in SendProducer.java: https://github.com/reactor/reactor-kafka/blob/main/src/main/java/reactor/kafka/sender/internals/SendSubscriber.java#L100

This is from the Reactor-Kafka internals, so there is no way for us to remove this log statement (we have now turned off kafka-logging entirely as a temporary workaround).

## Desired solution
Please remove this log statement (or log at debug/trace-level). An error is returned from this function anyways, so we can decide how to deal with the error case in our application code. There is no need imo to additionally log the error to console, at least not at error level, since it causes the aforementioned issues.

## Considered alternatives
Workaround is to disable kafka logging completely in config, but that's not great

**Comment by kotlinlukas** [comment]
Hello, any update on this?

**Comment by artembilan** [comment]
@kotlinlukas ,

Contribution is welcome!
Just open pull request with possible fix and we'll review it shortly.

Thanks

**Comment by garyrussell** [comment]
Closed by dfa65c34b4c8a6212c1de619487bcec57b708a2c
