### ISSUE TITLE
enable.auto.commit is always set to false

### ISSUE THREAD

**Issue by vinsguru** [reactor/reactor-kafka#326]
Hi Team,
Thanks for providing reactor support for Kafka.

I was confused why my config was NOT working for the property "enable.auto.commit".

```
var consumerConfig = Map.<String, Object>of(
        ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092",
        ConsumerConfig.GROUP_ID_CONFIG, "vins-group",
        ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class,
        ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class,
        ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest",
        ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, true
);
ReceiverOptions.create(consumerConfig)
       ....
       ....
```

then I found this override - https://github.com/reactor/reactor-kafka/blob/ede7c12678381558f52c5c3fe309e9db484d07b3/src/main/java/reactor/kafka/receiver/ImmutableReceiverOptions.java#L103

**_Just curious - why do we do that? Is it documented?_**

I have a work around though 

```
ReceiverOptions.create(consumerConfig)
                .consumerProperty("enable.auto.commit", true)
```

**Comment by garyrussell** [comment]
Auto commit is turned off because the framework provides a more reliable and deterministic mechanisms for committing offsets.

You should not enable it in the clients; see the documentation for the various commit options 

https://projectreactor.io/docs/kafka/release/reference/#api-guide-receiver
