### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by drmaas** [reactor/reactor-kafka#33]
Is this project actively maintained? I'm curious about the roadmap and plans for it going forward, if it's going to be actively developed or if it is recommended to use akka-kafka or kafka-streams instead.

**Comment by Cs4r** [comment]
lately the issues tracker seems to be so unatttended that I wonder if you'll get an answer from the maintainers 😞

**Comment by smaldini** [comment]
The lead contributor moved on and we were unable to maintain for a while given some massive undertaking in other areas like netty, core and other R&D effort.
We fortunately grew our team this year and we are envisioning a revival 👍 Alternatively this is a pretty good opportunity to step up as an external community champion to help us with the project. Fortunately its not in a bad state, the basics work correctly but it certainly needs love and attention if anyone is up for the challenge!

**Comment by OlegDokuka** [comment]
@Cs4r, @drmaas, currently, I'm taking the care of the project, so all question/issue will be addressed

**Comment by OlegDokuka** [comment]
close for now. Ping me if you have any question
