### ISSUE TITLE
[Enhancement request] reactiveKafkaConsumerTemplate.receiveAutoAck() => Flux<ConsumerRecord<String, String>> vs kafkaReceiver.receiveAutoAck() => Flux<Flux<ConsumerRecord<String, String>>

### ISSUE THREAD

**Issue by patpatpat123** [reactor/reactor-kafka#330]
## Documentation Issue
Currently, the documentation (well written by the way) provide explanations for the api ```reactiveKafkaConsumerTemplate.receiveAutoAck()``` which generates a ```Flux<ConsumerRecord<String, String>>```.

However, on the other hand, there is little document on``` kafkaReceiver.receiveAutoAck()``` which results to ```Flux<Flux<ConsumerRecord<String, String>>```

## Improvement Suggestion
Would it be possible to provide examples for both ```reactiveKafkaConsumerTemplate.receiveAutoAck()```  and ``` kafkaReceiver.receiveAutoAck()``` please? Both are possible ways to consume messages.

Moreover, I would like to highlight a possible confusion here. As the names suggest, both ```receiveAutoAck()``` methods are similar.

However, they are returning different things (a Flux of ConsumerRecord, vs a Flux of Flux of ConsumerRecord) which is a bit confusing.

Would it be possible to unify both APIs in the future please?

If not, would it be possible to have docs explaining the difference, as well as example for each please?

Thank you

**Comment by garyrussell** [comment]
>Moreover, I would like to highlight a possible confusion here. As the names suggest, both `receiveAutoAck()` methods are similar.

The template is not part of this project; it is just a lightweight wrapper around the `KafkaReceiver` in the `spring-kafka` project.

Most of its methods simply delegate to the underlying `KafkaReceiver`.

**Comment by patpatpat123** [comment]
Is it ok to ask for some sample with ```receiveAutoAck()``` please?

Something similar to this https://github.com/reactor/reactor-kafka/blob/main/reactor-kafka-samples/src/main/java/reactor/kafka/samples/SampleConsumer.java#L80 but with ```receiveAutoAck()```

**Comment by garyrussell** [comment]
Yes; it's ok to ask; just don't confuse the two separate projects.

The `Flux<Flux>` is because each poll returns a number of records; when the inner flux completes, its record offsets are automatically committed.

There is a test case here: 

https://github.com/reactor/reactor-kafka/blob/4b8ddb8dcee2f59a2ba503b6258eb53bd93c8d07/src/test/java/reactor/kafka/receiver/KafkaReceiverTest.java#L345-L347

As you can see, it simply uses `.concatMap()` to flatten the fluxes.

**Comment by patpatpat123** [comment]
Many thanks @garyrussell for the clear writing
