### ISSUE TITLE
Clarification on reactor.kafka.receiver.internals.ConsumerEventLoop.PollEvent<K, V> code

### ISSUE THREAD

**Issue by gauravsindhwani** [reactor/reactor-kafka#338]
Hi Folks,
While trying to understand how ConsumerEventLoop works, I figured out a potential anomaly 
in the class CosumerEventloop the onRequest Method adds toAdd records REQUESTED line no: 154
```
void onRequest(long toAdd) {
        if (log.isDebugEnabled()) {
            log.debug("onRequest.toAdd {}, paused {}", toAdd, pollEvent.isPaused());
        }
        Operators.addCap(REQUESTED, this, toAdd);
        if (pollEvent.isPaused()) {
            consumer.wakeup();
        }
        pollEvent.schedule();
    }
```

But when the records are emitted only 1 record is deducted from REQUESTED line no: 369
```
 if (!records.isEmpty()) {
                        this.commitBatch.addUncommitted(records);
                        r = Operators.produced(REQUESTED, ConsumerEventLoop.this, 1);
                        log.debug("Emitting {} records, requested now {}", records.count(), r);
                        sink.emitNext(records, ConsumerEventLoop.this);
                    }
```
should we not deduct records.count() instead of 1 , that is   r = Operators.produced(REQUESTED, ConsumerEventLoop.this, records.count());

Thank you

**Comment by garyrussell** [comment]
No; the loop emits `ConsumerRecords<?, ?>` which is a collection of records received from the poll. The request is for a batch of records.

**Comment by gauravsindhwani** [comment]
Thank you @garyrussell for clarification
