### ISSUE TITLE
Consumer lag is always zero

### ISSUE THREAD

**Issue by aqaexplorer** [reactor/reactor-kafka#347]
I am using reactor kafka 1.3.18 and spring boot 3.1.0. I have added MicrometerConsumerListener to have an ability to check metrics via app actuator.
The metric that I am checking is kafka.consumer.fetch.manager.records.lag

## Expected Behavior
Link - .../actuator/metrics/kafka.consumer.fetch.manager.records.lag
Value should show the real consumer lag

## Actual Behavior
Value is always zero

<img width="469" alt="Screenshot 2023-06-15 at 16 26 34" src="https://github.com/reactor/reactor-kafka/assets/34918217/63f2b741-a339-4fbc-99ec-a8df1d8d8299">

## Steps to Reproduce
Added consumer listener to Receiver Options
` ReceiverOptions.consumerListener(MicrometerConsumerListener(meterRegistry))`

Added metrics endpoint to spring configuration
`management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics`

Go to  .../actuator/metrics/kafka.consumer.fetch.manager.records.lag

* Reactor version(s) used: 1.3.18
* Other relevant libraries versions: spring boot 3.1.0
* JVM version: kotlin 1.8.21

**Comment by garyrussell** [comment]
This metric is maintained by the `kafka-clients` library and exposed by micrometer; it has nothing to do with this project; we just provide a mechanism to enable it.

If it is reported as zero, then it must be zero; you can verify using JMX.
