### ISSUE TITLE
IllegalStateException in KafkaReceiver.doOnConsumer() in case of subsequent subscription.

### ISSUE THREAD

**Issue by slimboyfat** [reactor/reactor-kafka#352]
Sometimes doOnConsumer() throws IllegalStateException during subsequent subscription.

## Expected Behavior

IllegalStateException should not be thrown.

## Actual Behavior

Sometimes IllegalStateException is thrown.

## Steps to Reproduce

```java
    @Test
    public void shouldNotFailOnSubsequentSubscriptionsWhenUseDoOnConsumer() {
        ConsumerFactory mockConsumerFactory = new ConsumerFactory() {

            @Override
            @SuppressWarnings("unchecked")
            public <K, V> org.apache.kafka.clients.consumer.Consumer<K, V> createConsumer(ReceiverOptions<K, V> config) {
                MockConsumer consumer = new MockConsumer(cluster);
                consumer.configure((ReceiverOptions<Integer, String>) config);
                return (org.apache.kafka.clients.consumer.Consumer<K, V>) consumer;
            }
        };
        receiverOptions = receiverOptions.subscription(Collections.singleton(topic));
        DefaultKafkaReceiver<Integer, String> receiver = new DefaultKafkaReceiver<>(mockConsumerFactory, receiverOptions);

        sendMessages(topic, 0, 1);

        for (int i = 0; i < 3; i++) {
            Map<String, List<PartitionInfo>> partitions = receiver.receive()
                .flatMap(rec -> receiver.doOnConsumer(consumer -> consumer.listTopics()))
                .blockFirst(Duration.ofMillis(DEFAULT_TEST_TIMEOUT));

            assertNotNull(partitions);
            assertFalse(partitions.isEmpty());
        }
    }
```

Test full test code can be found here https://github.com/reactor/reactor-kafka/compare/main...slimboyfat:reactor-kafka:main#diff-817d02b831d0354453445703e6b600278fadc84ee349e17bed637ffa06ff889eR1318-R1344

Some executions produce following output:

> [2023-06-28 20:48:09,482] [main] [reactor.kafka.receiver.internals.ConsumerEventLoop] DEBUG onRequest.toAdd 1, paused false
> [2023-06-28 20:48:09,485] [reactive-kafka-test-group-1] [reactor.kafka.receiver.internals.ConsumerEventLoop] DEBUG onPartitionsAssigned [topic2-1, topic2-0]
> [2023-06-28 20:48:09,500] [reactive-kafka-test-group-1] [reactor.kafka.receiver.internals.ConsumerEventLoop] DEBUG Emitting 1 records, requested now 0
> [2023-06-28 20:48:09,501] [reactive-kafka-test-group-1] [reactor.kafka.receiver.internals.ConsumerEventLoop] DEBUG onRequest.toAdd 1, paused false
> [2023-06-28 20:48:09,519] [reactive-kafka-test-group-1] [reactor.kafka.receiver.internals.ConsumerEventLoop] DEBUG Emitting 0 records, requested now 0
> [2023-06-28 20:48:09,519] [reactive-kafka-test-group-1] [reactor.kafka.receiver.internals.ConsumerEventLoop] DEBUG onRequest.toAdd 1, paused false
> [2023-06-28 20:48:09,530] [main] [reactor.kafka.receiver.internals.ConsumerEventLoop] DEBUG onRequest.toAdd 1, paused false
> [2023-06-28 20:48:09,530] [reactive-kafka-test-group-2] [reactor.kafka.receiver.internals.ConsumerEventLoop] DEBUG onPartitionsAssigned [topic2-1, topic2-0]
> [2023-06-28 20:48:09,535] [reactive-kafka-test-group-1] [reactor.kafka.receiver.internals.ConsumerEventLoop] DEBUG dispose true
> [2023-06-28 20:48:09,542] [reactive-kafka-test-group-2] [reactor.kafka.receiver.internals.ConsumerEventLoop] DEBUG Emitting 1 records, requested now 0
> [2023-06-28 20:48:09,543] [reactive-kafka-test-group-2] [reactor.kafka.receiver.internals.ConsumerEventLoop] DEBUG onRequest.toAdd 1, paused false
> [2023-06-28 20:48:09,550] [reactive-kafka-test-group-2] [reactor.kafka.receiver.internals.ConsumerEventLoop] DEBUG dispose true
> 
> java.lang.IllegalStateException: You must call one of receive*() methods before using doOnConsumer
> 
> 	at reactor.kafka.receiver.internals.DefaultKafkaReceiver.doOnConsumer(DefaultKafkaReceiver.java:128)
> 	at reactor.kafka.receiver.internals.MockReceiverTest.lambda$shouldNotFailOnSubsequentSubscriptionsWhenUseDoOnConsumer$98(MockReceiverTest.java:1337)
> 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:386)
> 	at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onNext(FluxUsingWhen.java:345)
> 	at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.onNext(FluxUsing.java:353)
> 	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
> 	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainAsync(FluxFlattenIterable.java:453)
> 	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:724)
> 	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.onNext(FluxFlattenIterable.java:256)
> 	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runBackfused(FluxPublishOn.java:484)
> 	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:521)
> 	at reactor.core.scheduler.ExecutorScheduler$ExecutorTrackedRunnable.run(ExecutorScheduler.java:192)
> 	at reactor.core.scheduler.ImmediateScheduler$ImmediateSchedulerWorker.schedule(ImmediateScheduler.java:84)
> 	at reactor.core.scheduler.SingleWorkerScheduler.execute(SingleWorkerScheduler.java:64)
> 	at reactor.core.scheduler.ExecutorScheduler$ExecutorSchedulerWorker.schedule(ExecutorScheduler.java:252)
> 	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.trySchedule(FluxPublishOn.java:312)
> 	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.onNext(FluxPublishOn.java:237)
> 	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210)
> 	at reactor.core.publisher.UnicastProcessor.drainRegular(UnicastProcessor.java:388)
> 	at reactor.core.publisher.UnicastProcessor.drain(UnicastProcessor.java:470)
> 	at reactor.core.publisher.UnicastProcessor.tryEmitNext(UnicastProcessor.java:338)
> 	at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100)
> 	at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
> 	at reactor.kafka.receiver.internals.ConsumerEventLoop$PollEvent.run(ConsumerEventLoop.java:371)
> 	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
> 	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
> 	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
> 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> ...
> 

## Possible Solution

I think the reason of such behaviour is asynchronous nature of Flux.usingWhen(...) - https://github.com/reactor/reactor-kafka/blob/main/src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java#L134

The cleanup action https://github.com/reactor/reactor-kafka/blob/main/src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java#L147 is executed asynchronously. 

There is no guarantee that cleanup (including consumerHandler = null) is executed before subsequent consumerHandler = new ConsumerHandler assignment https://github.com/reactor/reactor-kafka/blob/main/src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java#L135

I believe that Flux.using() will give right guarantee for cleanup.

#
## Your Environment

* Reactor version(s) used: reactor-core-3.4.30-SNAPSHOT
* Other relevant libraries versions (eg. `netty`, ...): n/a
* JVM version (`java -version`): openjdk version "11.0.7" 2020-04-14
* OS and version (eg `uname -a`): Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Dec 19 20:44:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_X86_64 x86_64

**Comment by garyrussell** [comment]
The use case is a bit unusual; generally the receiver is used for one receive, with a long-lived pipeline.

Contributions are welcome.

**Comment by garyrussell** [comment]
But, blocking on the close is probably not the correct solution.
