### ISSUE TITLE
Cannot add partition topic to transaction while in state  READY

### ISSUE THREAD

**Issue by yangwenliang123** [reactor/reactor-kafka#357]
spring.kafka.producer.properties.transactional.id=im_group
I opened the Kafka transaction. use reactiveKafkaProducerTemplate.send() API appearing exception: Cannot add partition topic to transaction while in state  READY. opening a transaction can only be used reactiveKafkaProducerTemplate.sendTransactionally() API?

**Comment by garyrussell** [comment]
>`spring.kafka.producer.properties.transactional.id`

This is a Spring Boot property for Spring for Apache Kafka, it has nothing to do with this project.

To enable transactions in reactor-kafka, set the `ProducerConfig.TRANSACTIONAL_ID_CONFIG` property (`transactional.id`) passed into the 

https://github.com/reactor/reactor-kafka/blob/a2c451564f4d8d14723f74a57af7f1df4d5d650a/src/main/java/reactor/kafka/sender/SenderOptions.java#L44-L50

when creating the `SenderOptions`.
