### ISSUE TITLE
reactor-kafka docs from 1.3.11 above referencing old 1.1.0.RELEASE docs

### ISSUE THREAD

**Issue by fabiojb** [reactor/reactor-kafka#358]
Incorrect documentation from reactor-kafka 1.3.11 above.

## Documentation Issue

Versions from reactor-kafka 1.3.10 (including) bellow show the correct documentation for its version, but from version 1.3.11 above, the documentation refers to an old version of reactor-kafka, as can be noticed in these links:

* Correct: https://projectreactor.io/docs/kafka/1.3.10/reference/index.html
* Incorrect: https://projectreactor.io/docs/kafka/1.3.11/reference/index.html (all versions from 1.3.11 are incorrect too)

The main doc page is incorrect too: 
* https://projectreactor.io/docs - "Reactor Kafka" section, select "Reference - Release" or "Reference - Snapshot" and it refers the old 1.1.0.RELEASE version.

Javadocs seems to be correct for all versions.

## Improvement Suggestion

Show the correct documentation for the specified version

## Additional context
![image](https://github.com/reactor/reactor-kafka/assets/12597490/82ffc0d0-d825-4f3a-9d85-ccbe37d42742)
![image](https://github.com/reactor/reactor-kafka/assets/12597490/04cd1865-3b1e-41aa-a9f9-a5b25d9a51a2)
![image](https://github.com/reactor/reactor-kafka/assets/12597490/606ea2e5-054f-4483-9155-39620c0dee90)

**Comment by artembilan** [comment]
On it. 
Thanks for reporting!

**Comment by artembilan** [comment]
So, the latest SNAPSHOT shows a correct version in the doc: https://projectreactor.io/docs/kafka/snapshot/reference/

**Comment by fabiojb** [comment]
@artembilan can also fix the links from the versions 1.3.11 to 1.3.20?

https://projectreactor.io/docs/kafka

**Comment by artembilan** [comment]
No, release one cannot be fixed. It is tagged therefore read only.
The best we can do is to wait for the next release in September.
