### ISSUE TITLE
Reference doc format error in "Sample Scenarios" header

### ISSUE THREAD

**Issue by michaelmcfadyensky** [reactor/reactor-kafka#360]
## Documentation Issue
On the [reference documentation](https://projectreactor.io/docs/kafka/release/reference/), there is a formatting error in the section header for `Sample Scenarios`. The text on the web page shows up as `== Sample Scenarios`. I believe `==` is used in ascii docs for denoting a section header.

I've attached a screenshot showing the issue.

## Improvement Suggestion
Ensure the section header format is applied correctly.

## Additional context

![Screenshot 2023-09-15 at 12 24 35](https://github.com/reactor/reactor-kafka/assets/22095551/3dbcce6f-0ef6-49a9-aa43-d145e6dd8583)

**Comment by artembilan** [comment]
That one has to be as a section title.
Please, consider to provide a fix with a PR where you would just add a blank line before that `== Sample Scenarios` one.
Thanks

**Comment by nikhilkarve** [comment]
May I fix this? @artembilan

**Comment by artembilan** [comment]
Sure thing, @nikhilkarve !

**Comment by nikhilkarve** [comment]
@artembilan Corrected that, can you take a look whenever you are available? 
https://github.com/reactor/reactor-kafka/pull/362
