### ISSUE TITLE
ClassCastException on attempt to get bootstrap server from SenderOption/ReceiverOptions

### ISSUE THREAD

**Issue by ajax-osadchuk-r** [reactor/reactor-kafka#374]
## Expected Behavior

`SenderOptions#bootstrapServers` and `ReceiverOptions#bootstrapServers` should sucessffully return bootstrap.servers config property value

## Actual Behavior
`SenderOptions#bootstrapServers` and `ReceiverOptions#bootstrapServers` throw next ClassCastException:

```
java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.lang.String (java.util.ArrayList and java.lang.String are in module java.base of loader 'bootstrap')
        at reactor.kafka.sender.SenderOptions.bootstrapServers(SenderOptions.java:289)
        
//------------------------------------------------------------------------------------------------------------------

java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.lang.String (java.util.ArrayList and java.lang.String are in module java.base of loader 'bootstrap')
        at reactor.kafka.receiver.ReceiverOptions.bootstrapServers(ReceiverOptions.java:573)        
```

that is because `SenderOptions#producerProperty` returns an instance of Object class, in case of `BOOTSTRAP_SERVERS_CONFIG` it is an object of List and it can not be casted to a String
<img width="892" alt="image" src="https://github.com/reactor/reactor-kafka/assets/111277666/d903e407-47b5-4aa7-b64c-d4202d5259d3">

## Steps to Reproduce

```java
@Test
void reproCase() {
        var kafkaProps =  new KafkaProperties();
        var senderOptions = SenderOptions.create(kafkaProps.buildProducerProperties());
        assertThrows(ClassCastException.class, senderOptions::bootstrapServers);

        var receiverOptions = ReceiverOptions.create(kafkaProps.buildConsumerProperties());
        assertThrows(ClassCastException.class, receiverOptions::bootstrapServers);
}
```

## Your Environment

* Reactor version(s) used: reactor-kafka:1.3.22, reactor-core:3.5.12
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`): 18
* OS and version (eg `uname -a`): MacOS 13.4

**Comment by sanderino666** [comment]
As a workaround, I did this:

```
Map<String, Object> props = kafkaProperties.buildProducerProperties(null);

//reactor-kafka 1.3.22 casts the given bootstrap servers arraylist to a string and throws a class cast exception
//https://github.com/reactor/reactor-kafka/issues/374
props.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, String.join(",", kafkaProperties.getProducer().getBootstrapServers()));

SenderOptions<String, CloudEvent> senderOptions = SenderOptions.create(props);
...
```
This is an example for the producer side, the same holds for the consumer side.

`kafkaProperties` is the `org.springframework.boot.autoconfigure.kafka.KafkaProperties` coming from the Spring Boot Kafka autoconfiguration.

**Comment by ajax-osadchuk-r** [comment]
> As a workaround, I did this:
> 
> ```
> Map<String, Object> props = kafkaProperties.buildProducerProperties(null);
> 
> //reactor-kafka 1.3.22 casts the given bootstrap servers arraylist to a string and throws a class cast exception
> //https://github.com/reactor/reactor-kafka/issues/374
> props.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, String.join(",", kafkaProperties.getProducer().getBootstrapServers()));
> 
> SenderOptions<String, CloudEvent> senderOptions = SenderOptions.create(props);
> ...
> ```
> 
> This is an example for the producer side, the same holds for the consumer side.
> 
> `kafkaProperties` is the `org.springframework.boot.autoconfigure.kafka.KafkaProperties` coming from the Spring Boot Kafka autoconfiguration.

Yes, a have sldo used such workaround, it works.

**Comment by emmanuelsilva** [comment]
Hey all, I also came across this class cast exception when using Spring Boot. I opened the merge request #376 to fix it in the library. Let's see how it goes.
