### ISSUE TITLE
Manual commit never completes

### ISSUE THREAD

**Issue by jurna** [reactor/reactor-kafka#4]
When commiting records manually (ReceiverRecord.offset().commit().block() ) - returned Mono never completes. That is because commit handler in KafkaConsumer is invoked in a poll loop. KafkaConsumer.poll is not called until commit is finished - we have a stall.

With acync commit result is the same when flow is backpressured due to queues becoming full.

**Comment by rajinisivaram** [comment]
@jurna Thank you for reporting this issue. This was missed out when moving from 0.10.0.1 (where regular polling for heartbeats took care of commits) to 0.10.1.0 (where heartbeat is built into `KafkaConsumer`). I have pushed a fix. It is in the latest build snapshot and will be available in the next milestone.
