### ISSUE TITLE
Manually stopped partitions should not be resumed by reactor-kafka

### ISSUE THREAD

**Issue by bsideup** [reactor/reactor-kafka#48]
Hi!

**Observed behaviour:**
If user manually stops some of the assigned partitions, `PollEvent` will resume it on a next flow control action:
https://github.com/reactor/reactor-kafka/blob/7a1bab38f92e0460185ce76ca09eb31c5d42b5f9/src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java#L475-L481

**Expected behaviour:**
Manually controlled partitions should be respected and not affected by `PollEvent`'s logic.

**Version:**
Both 1.0.0.RELEASE and latest master

**Comment by Delorien84** [comment]
I am voting for that issue. I want to just fill same issue. Currently I implemented ugly workaround, that check incoming records and  re-pause and seek the partition when additional messages comes, when it should not.

**Comment by garyrussell** [comment]
Fixed by https://github.com/reactor/reactor-kafka/pull/199 last year.
