### ISSUE TITLE
Apache Kafka 2.x.x support

### ISSUE THREAD

**Issue by OlegDokuka** [reactor/reactor-kafka#53]
http://mail-archives.us.apache.org/mod_mbox/www-announce/201807.mbox/%3CCAOJcB3-fryH23F4rirtdP+2e6sBqDL-qEQB+60p6ueOoM52Nvw@mail.gmail.com%3E

http://kafka.apache.org/20/documentation/streams/upgrade-guide

**Comment by unguiculus** [comment]
I noticed that support for 2.0.0 has landed on master. What is the timeline for a release? Maybe a milestone or RC could be published in the meatime?

**Comment by OlegDokuka** [comment]
It is available right now
