### ISSUE TITLE
Spring WebFlux example

### ISSUE THREAD

**Issue by artemyarulin** [reactor/reactor-kafka#56]
I'm trying to find a way how to use reactor-kafka with Spring WebFlux web service. Following is a working example and it works fine if there are no simultaneous calls involved.

Questions:
~~1. I do share `sender`, but if I run `while true; do curl http://localhost:8080/ping; done` from 3 terminals eventually one terminal would stuck, responses doesn't go though. Does it mean I cannot share it between requests?~~

2. With consumer I don't share it and create a new one every time because otherwise I get `Multiple subscribers are not supported for KafkaFlux`. It works fine with 1 `curl` client, but with multiple it becomes again very slow

I can create example repo, but following is essentially all the code but imports and Spring server run. 

```kotlin
@RestController
class Streamer {
    val sender = {
        val props = HashMap<String, Any>()
        props[ProducerConfig.BOOTSTRAP_SERVERS_CONFIG] = "localhost:9092"
        props[ProducerConfig.CLIENT_ID_CONFIG] = "streamer-ping"
        props[ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG] = StringSerializer::class.java
        props[ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG] = StringSerializer::class.java
        val senderOptions = SenderOptions.create<String, String>(props)
        KafkaSender.create(senderOptions)
    }()
    val options = {
        val props = HashMap<String, Any>()
        props[ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG] = "localhost:9092"
        props[ConsumerConfig.CLIENT_ID_CONFIG] = "streamer-pong"
        props[ConsumerConfig.GROUP_ID_CONFIG] = "streamer-pong-group"
        props[ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG] = StringDeserializer::class.java
        props[ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG] = StringDeserializer::class.java
        props[ConsumerConfig.AUTO_OFFSET_RESET_CONFIG] = "earliest"
        val options = ReceiverOptions.create<String, String>(props)
        options.subscription(listOf("test"))
    }()

    @GetMapping("ping")
    fun ping(): Flux<String> {
        val idx = Random().nextInt(1000)
        return sender
                .send(Flux.just(SenderRecord.create<String, String, String>(ProducerRecord("test", UUID.randomUUID().toString(), "$idx"), "String")))
                .map { "Ping $idx sent of offset ${it.recordMetadata().offset()}" }
    }

    @GetMapping("pong")
    fun pong(): Flux<String> {
        return KafkaReceiver.create(options)
                .receive()
                .map {
                    it.receiverOffset().acknowledge()
                    "Pong ${it.value()} received from offset ${it.offset()}"
                }.take(1)
    }
```

**Comment by artemyarulin** [comment]
Sorry, my laptop simply wasn't able to handle that load with sender, so first question is solved :) 

But consuming is still relevant — what is the correct way to share that between simultaneous requests?

**Comment by OlegDokuka** [comment]
Hey @artemyarulinl. In order to share data from the same consumer, you may use the operator `.publish` or use some of the reactor's processors. For example: 

```
@RestController
class Streamer {
    val receiver = KafkaReceiver.create(options)
                                .receive()
                                .map {
                                   it.receiverOffset().acknowledge()
                                   "Pong ${it.value()} received from offset ${it.offset()}"
                                }
    val processor = receiver.subscribeWith(EmitterProcessor.create());

    val sender = {
        val props = HashMap<String, Any>()
        props[ProducerConfig.BOOTSTRAP_SERVERS_CONFIG] = "localhost:9092"
        props[ProducerConfig.CLIENT_ID_CONFIG] = "streamer-ping"
        props[ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG] = StringSerializer::class.java
        props[ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG] = StringSerializer::class.java
        val senderOptions = SenderOptions.create<String, String>(props)
        KafkaSender.create(senderOptions)
    }()
    val options = {
        val props = HashMap<String, Any>()
        props[ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG] = "localhost:9092"
        props[ConsumerConfig.CLIENT_ID_CONFIG] = "streamer-pong"
        props[ConsumerConfig.GROUP_ID_CONFIG] = "streamer-pong-group"
        props[ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG] = StringDeserializer::class.java
        props[ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG] = StringDeserializer::class.java
        props[ConsumerConfig.AUTO_OFFSET_RESET_CONFIG] = "earliest"
        val options = ReceiverOptions.create<String, String>(props)
        options.subscription(listOf("test"))
    }()

    @GetMapping("ping")
    fun ping(): Flux<String> {
        val idx = Random().nextInt(1000)
        return sender
                .send(Flux.just(SenderRecord.create<String, String, String>(ProducerRecord("test", UUID.randomUUID().toString(), "$idx"), "String")))
                .map { "Ping $idx sent of offset ${it.recordMetadata().offset()}" }
    }

    @GetMapping("pong")
    fun pong(): Flux<String> {
        return processor.take(1);
    }
```


Should be like that. Test it and let me know whether it solved your problem )

**Comment by artemyarulin** [comment]
Works! `receiver.subscribeWith(EmitterProcessor.create(false));` has to be set, and then it works, thank you! 🎉 😄

**Comment by artemyarulin** [comment]
Adding a bit more info

Just found out that EmitterProcessor in this example wouldn't constantly keep consuming items from KafkaReceiver but would consume only few items (256 by default) and wait until any subscriber ready to take more (in this example - GET handler and `processor.take(1)`). So in this case it brings two issues:
- Consume lag as we produce more messages and consumption depends on random HTTP calls
- HTTP call after delay returns not recent item, but item from past

Correct way is just create `hot` publisher:
```kotlin
val receiver = KafkaReceiver.create(options)
                                .receive()
                                .map {
                                   it.receiverOffset().acknowledge()
                                   "Pong ${it.value()} received from offset ${it.offset()}"
                                }
receiver.publish() // Create hot publisher, consumes items without waiting for subscribers
receiver.connect() // Run hot publisher
```
So any new subscribers would receive only items that were added to receiver after subscription and multiple subscribers can do that simultaneously

**Comment by arsalans** [comment]
> Adding a bit more info
> 
> Just found out that EmitterProcessor in this example wouldn't constantly keep consuming items from KafkaReceiver but would consume only few items (256 by default) and wait until any subscriber ready to take more (in this example - GET handler and `processor.take(1)`). So in this case it brings two issues:
> 
> * Consume lag as we produce more messages and consumption depends on random HTTP calls
> * HTTP call after delay returns not recent item, but item from past
> 
> Correct way is just create `hot` publisher:
> 
> ```kotlin
> val receiver = KafkaReceiver.create(options)
>                                 .receive()
>                                 .map {
>                                    it.receiverOffset().acknowledge()
>                                    "Pong ${it.value()} received from offset ${it.offset()}"
>                                 }
> receiver.publish() // Create hot publisher, consumes items without waiting for subscribers
> receiver.connect() // Run hot publisher
> ```
> 
> So any new subscribers would receive only items that were added to receiver after subscription and multiple subscribers can do that simultaneously

Do you have a working example of this code somewhere, I am wondering how to call this hot publisher from within a rest controller. Thank you.

**Comment by rodrigo-loza-mojix** [comment]
Another way to have this done is to encapsulate the Kafka receiver in a singleton. Not sure if very correct though. Nonetheless I leave it here in case anyone needs it. 

```java
  @Autowired
  private KafkaReceiver<String,String> kafkaReceiver;
  @GetMapping(produces = MediaType.APPLICATION_STREAM_JSON_VALUE)
  public Flux getEventsFlux() {
    var kafkaFluxSingleton = KafkaReceiverSingleton.getInstance(kafkaReceiver);
    return kafkaFluxSingleton.getKafkaFlux()
        .checkpoint("Starting kafka message streaming.")
        .log()
        .doOnNext(record -> record.receiverOffset().acknowledge())
        .map(record -> processRecord(record))
        .checkpoint("Ending kafka message streaming.");
```

```java
public class KafkaReceiverSingleton {

  private static KafkaReceiverSingleton single_instance = null;
  private Flux<ReceiverRecord<String, String>> kafkaFlux;

  private KafkaReceiverSingleton(KafkaReceiver<String,String> kafkaReceiver) {
    kafkaFlux = kafkaReceiver
                  .receive()
                  .subscribeWith(EmitterProcessor.create(false));
  }

  public static KafkaReceiverSingleton getInstance(KafkaReceiver<String,String> kafkaReceiver) {
    if (single_instance == null)
      single_instance = new KafkaReceiverSingleton(kafkaReceiver);
    return single_instance;
  }

  public static KafkaReceiverSingleton getSingle_instance() {
    return single_instance;
  }

  public static void setSingle_instance(KafkaReceiverSingleton single_instance) {
    KafkaReceiverSingleton.single_instance = single_instance;
  }

  public Flux<ReceiverRecord<String, String>> getKafkaFlux() {
    return kafkaFlux;
  }

  public void setKafkaFlux(Flux<ReceiverRecord<String, String>> kafkaFlux) {
    this.kafkaFlux = kafkaFlux;
  }

}
```
