### ISSUE TITLE
Sample needed | Long running Kafka consumer

### ISSUE THREAD

**Issue by tosheer** [reactor/reactor-kafka#62]
I have a business process which continuously consumes data from kafka and put it into cassandra. I am using the Spring Boot 2.0 with Reactor Kafka. I can see a lot of examples like https://github.com/reactor/reactor-kafka/blob/master/reactor-kafka-samples/src/main/java/reactor/kafka/samples/SampleConsumer.java which reads the data from kafka and die. But nothing like KafkaListener which listens to any change message pushed to the topic and is a long running service.

How can i achieve this in Reactor Kafka world? As this is most common case for kafka consumers.

**Comment by hartmut-co-uk** [comment]
@tosheer have you found a working solution?

**Comment by hartmut-co-uk** [comment]
ref: https://github.com/spring-projects/spring-kafka/pull/1123
