### ISSUE TITLE
Kafka-client poll(timeout) is blocking method,  so that is not Real Async even if usr reactor-kafka

### ISSUE THREAD

**Issue by javait90** [reactor/reactor-kafka#63]
Kafka-client poll(timeout) is a block method,  so that is not Real Async even if using reactor-kafka

**Comment by OlegDokuka** [comment]
That is true. AFAIR, Kafka Client's API does not expose non-blocking access to the broker, so there is no other options than blocking poll in the separate thread, which performs good enough
