### ISSUE TITLE
Check if connection to broker is alive

### ISSUE THREAD

**Issue by grigorryev** [reactor/reactor-kafka#69]
Hi!

Is there any way to programmatically check if my consumer is successfully connected to the broker and ready to consume messages? I need this to implement some kind of health checks mechanism.

Thanks!

**Comment by yevtsy** [comment]
First of all, let's say when Kafka consumer connects to a broker and some exception occurs, the library considers every failure to be retryable, and does exactly this, retries forever, never returning an error to the client (moreover, it cannot tell the difference between a temporary failure, a permanent failure or a misconfiguration)

So, the workaround is to check the state of the connection: ask for something that is guaranteed to return, wait for some reasonable time and if nothing returns then you know that the connection has some problems

For example, org.apache.kafka.clients.consumer.KafkaConsumer has method listTopics() which has a timeout.
```
/**
 * Get metadata about partitions for all topics that the user is authorized to view. This method will issue a
 * remote call to the server.

 * @return The map of topics and its partitions
 *
 * @throws org.apache.kafka.common.errors.WakeupException if {@link #wakeup()} is called before or while this
 *             function is called
 * @throws org.apache.kafka.common.errors.InterruptException if the calling thread is interrupted before or while
 *             this function is called
 * @throws org.apache.kafka.common.KafkaException for any other unrecoverable errors
 * @throws org.apache.kafka.common.errors.TimeoutException if the offset metadata could not be fetched before
 *         the amount of time allocated by {@code default.api.timeout.ms} expires.
 */
@Override
public Map<String, List<PartitionInfo>> listTopics() {
    return listTopics(Duration.ofMillis(defaultApiTimeoutMs));
}
```
In case of any error, an exception will be thrown. Based on this we can simply wrap the check to this pipeline (look at the `doOnConsumer` method of [KafkaReceiver](https://github.com/reactor/reactor-kafka/blob/master/src/main/java/reactor/kafka/receiver/KafkaReceiver.java) ) and add to client
```
receiver.doOnConsumer(consumer -> consumer.listTopics())
     .doOnError(error -> System.out.println("Consumer cannot connect to broker and fetch metadata: []" + error));
```

Also I think it would be better to have API method on KafkaReceiver that makes more complex verification similar to `kafka-streams` health indicators: status, details, etc 
@smaldini @OlegDokuka what do you think about it?

**Comment by bsideup** [comment]
you can either use `kafka-clients` directly or see `doOnConsumer`
