### ISSUE TITLE
`stopOnError` not observed on Producer sending

### ISSUE THREAD

**Issue by Sage-Pierce** [reactor/reactor-kafka#72]
I have configured a KafkaSender to not stop on Errors (`stopOnError` == false) which is observed for Exceptions contained in callback Responses. However, this flag is _not_ observed for Exceptions resulting from the process of actually sending ProducerRecords:

https://github.com/reactor/reactor-kafka/blob/master/src/main/java/reactor/kafka/sender/internals/DefaultKafkaSender.java#L276

https://github.com/reactor/reactor-kafka/blob/master/src/main/java/reactor/kafka/sender/internals/DefaultKafkaSender.java#L283

https://github.com/reactor/reactor-kafka/blob/master/src/main/java/reactor/kafka/sender/internals/DefaultKafkaSender.java#L293

I have a case where I would like to continue processing Records on outbound Publishers even if a serialization Exception happens, which I can then handle downstream without the SendSubscriber fatally erroring out. This is useful when serialization is fallible; I use Avro which is dependent on network calls (but is recoverable) and there are cases where data is just not serializable, in which case I just want to log an Error and continue.

I believe this is a simple one-line change to have the `true` on line 293 swapped with `stopOnError`

**Comment by bsideup** [comment]
Fixed in #73
