### ISSUE TITLE
UNKNOWN_TOPIC_OR_PARTITION

### ISSUE THREAD

**Issue by ksinghbora** [reactor/reactor-kafka#74]
While setting auto.create.topics.enable=false in kafka broker I am getting message on client side

`[reactive-kafka-consumer-groupId-X] [31mWARN [0;39m o.apache.kafka.clients.NetworkClient - [Consumer clientId=, groupId=consumer-groupId] Error while fetching metadata with correlation id {XXX=UNKNOWN_TOPIC_OR_PARTITION}`

I want to handle the error if topic is not already created.

I am trying to catch the error using doOnError/onErrorMap. Look like it is not throwing error and internally keep retrying.
Any way to catch the error and hadle explictly?

**Comment by cricket007** [comment]
This is a warning, not an exception. Any consumer will keep retrying until the topic exists.

You'd have to try and describe the topic ahead of defining the consumer if you want to catch this
