### ISSUE TITLE
DefaultKafkaReceiver does not respect requested count

### ISSUE THREAD

**Issue by Delorien84** [reactor/reactor-kafka#76]
Hi,
 we have following simple receiver and Kafka Topic with tens of thousand unread messages.

```
receiver
  .receive()
  .flatMap(record -> Mono.just(record).delay(Duration.miliseconds(100)))`
  .onNext(record -> record.acknowledge())
  .subscribe()
```

The problem is with `reactor.kafka.receiver.internals.DefaultKafkaReceiver.requestsPending` counter in `reactor.kafka.receiver.internals.DefaultKafkaReceiver.withDoOnRequest(Flux<T>)` method. When the counter is negative and upstream request small amount data, the result of the method is counter with `Long.MAX_VALUE`.

That effectively leads into _infinite_ pool loop. Reading all _unread_ message from the topic. Leading into out of memory.

Currently this block us to upgrade to newer version.

Affected versions: 1.0.1 (1.1.0 - very likely, not tested)
Working version: 1.0.0

**Comment by bsideup** [comment]
Hi @Delorien84,

It might be unrelated, but still important:
I highly recommend changing `flatMap` here to `concatMap` because `flatMap` is concurrent and `record.acknowledge()` in `onNext` might ACK records in this order: 1, 2, 8, 4, 3, 7, 5, 6. Or *at least* `.flatMapSequential`.
You could also use `groupBy(record -> record.partition())` to make use if the partitions on this scheme.

**Comment by Delorien84** [comment]
Thank you @bsideup  it is unrelated. I am aware of the problem of ordering `record.acknowledge()`. That was just example. I and I think it will cause same problem, even I use `concatMap`. I  implement additional logic to process records in specific order and logic, to call `record.acknowledge()` in right sequence. Because I need to process records with same `key` in order and records with different `key` s may be process in parallel. Because there are a lot of `key`s, I cannot use `groupBy(record -> record.key())`. At least I think I cannot. As `flatMap` request maximum 256 records, I am save with memory and maximum number of parallel processed records.

Thank for the hint  `groupBy(record -> record.partition())`. I do not think so, it may simplify some logic.

I may expose the code if you are interested.

**Comment by bsideup** [comment]
@Delorien84 at my previous job, we were doing the same (per key processing).
Grouping by key is not efficient, yes, but per partition is okay, because all records with the same key will go into the same partition and the order will be guaranteed :)

**Comment by Delorien84** [comment]
@bsideup  yes you are right. The service will be busy, handling different partitions, so I may not need to implement complex logic to process messages from one partition in parallel and reordering the `acknowledge` command. Thank you for hints.

But back to the original problem. I think, that following code will cause `requestsPending` to become `Long.MAX_VALUE`, in case `requestsPending` is negative. As may happened in `PollEvent`. That will effectively read all messages from Kafka, causing `OutOfMemoryException`. For us, we hit `OutOfMemoryException` in less then seconds until service start.

```
private <T> Flux<T> withDoOnRequest(Flux<T> consumerFlux) {
        return consumerFlux.doOnRequest(toAdd -> {
            long r, u;
            for (;;) {
                r = requestsPending.get();
                if (r == Long.MAX_VALUE) {
                    pollEvent.scheduleIfRequired();
                    return;
                }
                u = Operators.addCap(r, toAdd);
                if (requestsPending.compareAndSet(r, u)) {
                    if (u > 0) {
                        pollEvent.scheduleIfRequired();
                    }
                    return;
                }
            }
        });
    }
```
