### ISSUE TITLE
Exactly-once transactions should end also when subscription cancelled

### ISSUE THREAD

**Issue by lbovet** [reactor/reactor-kafka#79]
When cancelling the subscription to a batch of records, I expect that the transaction closes and that polling resumes.
We can do that by replacing `doAfterTerminate` with `doFinally` in

https://github.com/reactor/reactor-kafka/blob/master/src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java#L211

This would allow to retry reading failing batches by aborting the transaction and resetting offsets. Currently, the consumer stays in pause mode if we don't consume the batch completely.

Alternatively, `awaitingTransaction` could be bound to the transactionManager state. Thus, upon abort, the consumer would resume. This is however a bigger change.

**Comment by bsideup** [comment]
Should be fixed in `1.3.0.RELEASE`
