### ISSUE TITLE
Kafka receiver stop consuming without noticeable reason under load 

### ISSUE THREAD

**Issue by iferca** [reactor/reactor-kafka#8]
I’m having a problem with reactor Kafka receivers that stop consuming messages randomly under (not heavy at all) load. I have some services that creates consumers from an API I’m creating based on reactor Kafka.
This is what I’m doing:
My consumer properties:
```
public Properties kafkaConsumerProperties() {
        Properties props = new Properties();
        props.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, properties.getBrokerAddress());
        props.put(ConsumerConfig.GROUP_ID_CONFIG, properties.getGroupId());
        props.put(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, "true");
        props.put(ConsumerConfig.AUTO_COMMIT_INTERVAL_MS_CONFIG, "1000");
        props.put(ConsumerConfig.MAX_POLL_RECORDS_CONFIG, 10);
        props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.StringDeserializer");
        props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.StringDeserializer");
        addSSLPropertiesIfPresent(props, properties);
        return props;
    }
```
Create new receiver:
```
public Receiver<String, String> newReceiver(String topic){
        ReceiverOptions<String, String> receiverOptions = ReceiverOptions.create(kafkaConsumerProperties);
        receiverOptions.subscription(Collections.singleton(topic));
        return reactor.kafka.receiver.Receiver.create(receiverOptions);
    }
```
```
private Flux<ReceiverRecord<String, String>> createNewReceiverForTopic(String topic) {
        return receiverFactory.newReceiver(topic)
                .receive().subscribeOn(Schedulers.parallel());
    }
```
This is how the receivers are created: I’m using annotation based configuration so I invoke this after I look for @Bean Consumer<String> decorated with @EventConsumer(topic = “my.topic”) and create a receiver for that topic, then subscribe the Consumer<String> to it:
```
createNewReceiverForTopic(topic)
    .doOnError(throwable -> log.error("Unexpected error in kafka flow for Consumer {}. {}::{}",
                                                    consumer.getClass().getName(), throwable.getClass().getName(), throwable.getMessage()))
    .doFinally(signalType -> System.out.println(signalType))
    .doOnNext(record -> processMessage(consumer, record))
    .subscribe();
```
This is how I invoke the Consumers:
```
private Try<Void> processMessage(Consumer<String> consumer, ReceiverRecord<String, String> record) {
        return Try.run(() -> consumer.accept(record.value()))
                .onSuccess(__ -> record.receiverOffset().acknowledge())
                .onFailure(throwable -> log.error("Error processing message {} in Consumer {}. {}::{}",
                        record.value(), consumer.getClass().getName(), throwable.getClass().getName(), throwable.getMessage()));
    }
```
I’d appreciate any hint: I’m using reactor-kaka 1.0.0.BUILD-SNAPSHOT & reactor-core 3.0.7.RELEASE.

I checked the status of the Flux I create and they are not disposed when they stop consuming and the application is responsible like in accepting HTTP request, etc

**Comment by iferca** [comment]
As suggested by @smaldini in Gitter I upgraded to reactor-core 3.1.0-M2 and the problem seems to fade away 👍 Keep testing it though

**Comment by ilayaperumalg** [comment]
@iferca I am closing this for now and feel free to re-open if you encounter any similar issue.

Thanks!

**Comment by CluEleSsUK** [comment]
I have encountered the same issue; neither `Flux.defer()` nor upgrading to 1.0.1.RELEAES nor upgrading reactor-core seems to work, and the number of messages that get consumed before going idle seems to be consistent.
If I replace the `KafkaReceiver` with the Spring `@KafkaListener` annotation, all the messages are processed.
