### ISSUE TITLE
How to delay message consumption

### ISSUE THREAD

**Issue by fletchgqc** [reactor/reactor-kafka#89]
We are using retry topics for failed messages. We receive a message from Kafka, process, and then acknowledge the offset manually. If an error occurs during processing, we write the message to a retry topic. The retry topics are handled in the same way, but message processing is exponentially delayed (first retry topic 5 minute delay, second retry topic 1 hr delay...).

The question is: how should we achieve the delay on the retry topics? 

Current approach: `KafkaReceiver.receive().delaySequence(delay);`

Problem: When trying to acknowledge the messages, a CommitFailedException is thrown. It seems to me that the messages are read from Kafka, then delayed, resulting in a timeout before the commit actually happens. I had hoped that the delaySequence would be like a form of backpressure or work in a lazy way, i.e. a message would not be read from Kafka until the delay expires.

Why doesn't delaySequence() interact with Kafka in the way I expect, and what would be the best way to delay message processing and still have a short time between reading and committing offset?

**Comment by maitreyak** [comment]
If the delay is longer than the max.poll.interval.ms (default=5 mins) you will end up in this situation. Set max.poll.interval.ms > max delay.  The reason being they are no PollEvents generated during the delay if no poll events for more than max.poll.interval.ms, the underlying Kafka consumer (the one reactor client wraps) shuts down the consumer, triggering a rebalance.

**Comment by fletchgqc** [comment]
OK thanks. Yes, I figured out in the meantime that it's impossible to delay items in a sequence without first receiving them. Otherwise, you can't delay them for a specific time from reception, which is what I'm trying to do.

**Comment by alwaysastudent** [comment]
@fletchgqc - what did you end up doing ? How did you implement the retry mechanism ?

**Comment by fletchgqc** [comment]
@alwaysastudent I left the project around the time that we were struggling with this. I can't actually remember whether we came up with a good solution. We were looking at reading timestamps in the message itself to determine the delay... I think we combined this with ensuring we are only processing one message at a time. I can't remember anything more, sorry.
