### ISSUE TITLE
compatibility between reactor kafka with kafka clients

### ISSUE THREAD

**Issue by 359557728** [reactor/reactor-kafka#9]
![image](https://user-images.githubusercontent.com/3425830/28205578-30ec3736-68b5-11e7-87f9-0ca1ca9af74c.png)
as pointed in the refrence, kafka client version must equal or lower than the broker version。
if you hava a kafka cluster(version 0.10.1.0) connected with reactor kafka(version M2) and java kakfa-clients(version lower than 0.10.2.0 ), it will failed.
because ReceiverRecord in reactor kafka(version M2) extends ConsumerRecord, but ConsumerRecord in kafka-clients(version lower than 0.10.2.0) is final. so the reactor reactor kafka(version M2) has compatibility issue with java kafka-client(version lower than 0.10.2.0), is any plan to solve this problem or any advice.

**Comment by rajinisivaram** [comment]
@359557728 As of Kafka version 0.10.2, new versions of clients can be used with older versions of brokers. So you should be able to use reactor-kafka with kafka client 0.10.2.2 or 0.11.0 and connect to a 0.10.1 broker. I will update the docs. Please update this issue if that doesn't work for you. Thank you!

**Comment by 359557728** [comment]
@rajinisivaram yes,
![image](https://user-images.githubusercontent.com/3425830/28299769-b665ab0e-6bad-11e7-8c91-bdeb8149cf8a.png) this combination works well with broker(version 0.10.1.0), i try it today, thanks for your advice.
