### ISSUE TITLE
Still no release with bugfix #76

### ISSUE THREAD

**Issue by naorgu** [reactor/reactor-kafka#92]
Hi

We experience the issue described in issue #76 (fixed by PR #77)
Looks like it is also requested by @jli207 [https://github.com/reactor/reactor-kafka/pull/77#issuecomment-486517674](https://github.com/reactor/reactor-kafka/pull/77#issuecomment-486517674)

Can we publish the new release into the maven repository?

Thanks

**Comment by joschi** [comment]
The changes from PR #77 have been part of the following releases:
* v1.2.2.RELEASE
* v1.2.1.RELEASE
* v1.2.0.RELEASE
* v1.1.2.RELEASE
* v1.1.1.RELEASE

I guess this issue can be closed.
