### ISSUE TITLE
Fail to receive message in consumer

### ISSUE THREAD

**Issue by meghagupta9** [reactor/reactor-kafka#95]
getting below error 

reactor-kafka 
<dependency>
    <groupId>io.projectreactor.kafka</groupId>
    <artifactId>reactor-kafka</artifactId>
    <version>1.1.1.RELEASE</version>
</dependency>

"msg":"KafkaScheduler worker in group main failed with an uncaught exception","stacktrace":["java.lang.NoSuchMethodError: org.apache.kafka.clients.consumer.Consumer.poll(Ljava/time/Duration;)Lorg/apache/kafka/clients/consumer/ConsumerRecords;","\tat reactor.kafka.receiver.internals.DefaultKafkaReceiver$PollEvent.run(DefaultKafkaReceiver.java:470)","\tat reactor.kafka.receiver.internals.DefaultKafkaReceiver.doEvent(DefaultKafkaReceiver.java:401)","\tat reactor.kafka.receiver.internals.DefaultKafkaReceiver.lambda$start$14(DefaultKafkaReceiver.java:335)","\tat reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:130)","\tat reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:398)","\tat reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:484)","\tat reactor.kafka.receiver.internals.KafkaSchedulers$EventScheduler.lambda$decorate$1(KafkaSchedulers.java:100)","\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)","\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)","\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)","\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)","\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)","\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)","\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)","\tat java.lang.Thread.run(Thread.java:836)"]}

**Comment by bsideup** [comment]
Hi @meghagupta9,

It looks like you're using a very old version of Kafka Client. Could you please share it too?

**Comment by meghagupta9** [comment]
Hi @bsideup,
Thanks for quick reply. 
I tried with **kafka-client 2.2.0 and reactor-kafka 1.1.1.release** 
facing below issue:
[org.springframework.boot.loader.LaunchedURLClassLoader [id=11212,parents=System@7439]]","\tat org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:507)","\tat org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:404)","\tat org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:389)","\tat org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:248)","\t... 24 more","Caused by: java.lang.NoClassDefFoundError: org/apache/kafka/clients/consumer/ConsumerRecord","\tat java.lang.ClassLoader.defineClass1(Native Method)","\tat java.lang.ClassLoader.defineClass(ClassLoader.java:858)","\tat java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)","\tat java.net.URLClassLoader.defineClass(URLClassLoader.java:530)","\tat java.net.URLClassLoader.access$100(URLClassLoader.java:76)","\tat java.net.URLClassLoader$1.run(URLClassLoader.java:431)","\tat java.net.URLClassLoader$1.run(URLClassLoader.java:425)","\tat java.security.AccessController.doPrivileged(Native Method)","\tat java.net.URLClassLoader.findClass(URLClassLoader.java:424)","\tat java.lang.ClassLoader.loadClass(ClassLoader.java:486)","\tat org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)","\tat java.lang.ClassLoader.loadClass(ClassLoader.java:419)","\tat java.lang.Class.getDeclaredMethods0(Native Method)","\tat java.lang.Class.privateGetDeclaredMethods(Class.java:2724)","\tat java.lang.Class.getDeclaredMethods(Class.java:1998)","\tat org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:489)","\t... 27 more","Caused by: java.lang.ClassNotFoundException: org.apache.kafka.clients.consumer.ConsumerRecord","\tat java.net.URLClassLoader$1.run(URLClassLoader.java:433)","\tat java.net.URLClassLoader$1.run(URLClassLoader.java:425)","\tat java.security.AccessController.doPrivileged(Native Method)","\tat java.net.URLClassLoader.findClass(URLClassLoader.java:424)","\tat java.lang.ClassLoader.loadClass(ClassLoader.java:486)","\tat org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)","\tat java.lang.ClassLoader.loadClass(ClassLoader.java:419)","\t... 43 more","Caused by: java.util.zip.ZipException: invalid block type","\tat java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)","\tat org.springframework.boot.loader.jar.ZipInflaterInputStream.read(ZipInflaterInputStream.java:52)","\tat sun.misc.Resource.getBytes(Resource.java:124)","\tat java.net.URLClassLoader.defineClass(URLClassLoader.java:525)","\tat java.net.URLClassLoader.access$100(URLClassLoader.java:76)","\tat java.net.URLClassLoader$1.run(URLClassLoader.java:431)","\t... 49 more"]}

Regards,
Megha

**Comment by meghagupta9** [comment]
Thanks @bsideup 
above issue is resolved with kafka-client 2.1.1

Now its failing with issue Connection to node -3 failed authentication due to: SSL handshake failed

Is there any I should set.

Tried adding  ssl.endpoint.identification.algorithm as an empty string, it did not help

**Comment by bsideup** [comment]
@meghagupta9 in this case, I would recommend asking help in Kafka community. `reactor-kafka` is a wrapper around the original Kafka client and we do not manage the SSL or anything.
